<<<<<<< HEAD
version: '3.8'
services:
  stocksshiny:
    image: fossengineer/r_stocks
    container_name: r_stocksshiny
    ports:
      - 3838:3838
    networks:                   #optional
      - cloudflare_tunnel       #optional
    restart: unless-stopped

networks:             #optional
  cloudflare_tunnel:  #optional
    external: true    #optional
=======
version: '3.8'
services:
  r_stocks_shiny:
    image: fossengineer/r_stocks
    container_name: r_stocks
    ports:
      - 3838:3838
    restart: unless-stopped      
>>>>>>> ff93b1dbebe5e4d483f1be571a04d5b8ff8d7ddf
