---
title: "R_Stocks_Shiny"
author: "JAT"
date: '2022-12-03'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Libraries needed - Installation}
#Required for the first use of the program in a device


# install.packages(c("rlang","devtools"), dependencies = TRUE)

#install.packages("BatchGetSymbols") #substituted for yfR
#devtools::install_github('msperlin/yfR') #yfR install option 1
#install.packages('yfR', dependencies = TRUE) #yfR install option 2
#install.packages("priceR", dependencies = TRUE) 
#install.packages("Quandl", dependencies = TRUE) #API key needed
#install.packages("quantmod", dependencies = TRUE) 
#install.packages("qmao", repos="http://R-Forge.R-project.org", dependencies = TRUE)
#install.packages("yaml")

# install.packages(c("tibble", "dplyr","writexl","shiny","shinythemes","shinyWidgets","scales","readxl","dtplyr","tidyverse","DT","ggthemes","plotly","plyr","leaflet","ggplot2","lubridate","reshape2"), dependencies = TRUE) 



```

```{r Libraries check}
#If needed for debugging



# pkg = tibble::tibble(
#   Package = names(installed.packages()[,3]),
#   Version = unname(installed.packages()[,3])
# )
# 
# 
# pkg_filtered=dplyr::filter(pkg, Package %in% c("tibble","yfR","priceR","Quandl","quantmod","qmao" "dplyr","shiny","shinythemes","shinyWidgets","scales","readxl","dtplyr","tidyverse","DT","ggthemes","plotly","plyr","leaflet","devtools","ggplot2","rlang"))

#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

#write.csv(pkg_filtered,paste(getwd(),"/pkgs_your_name.csv",sep=""), row.names = FALSE)


#packageVersion("rlang")
#"rlang" %in% loadedNamespaces()

```


```{r Load the libraries}




setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
#setwd("C:/Users/your/windows/path")

# Get your API key from quandl.com and include it on a 'config.yaml' file
library("yaml") 
vars = yaml.load_file("config.yml")
quandl_api = vars$config$quandl_api
 



#library('data.table')

#install.packages("pacman")
pacman::p_load(dplyr,dtplyr, shiny, shinythemes,shinyWidgets,readxl,scales,tidyverse,DT,ggthemes,ggplot2,plotly,plyr,leaflet,devtools,yaml)

#library("BatchGetSymbols") #depricated --->yfR

library("yfR") #historical stock valuation -> Instead of BatchGetSymbols
library("priceR") #inflation / currency exchange ===> adjust_for_inflation
library("quantmod") #dividends (getDividends), metals price
library("Quandl")   #EPS, debt, assets (#API key needed)

# Add the key to the Quandl keychain
Quandl.api_key(quandl_api)


library("qmao") #quand mod add ons -> EPS
library("dplyr")
library("lubridate")
library('plotly')
library("readxl")
library("ggplot2")
library("reshape2")
library("rstudioapi")



library(shiny)
library(shinythemes)
library(shinyWidgets)



library(DT)

getwd()

```


```{r Portfolio - read from excel}

# set as direction the one of .Rmd archive; .xlsx and .Rmd mut be on same folder
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
  
my_portfolio <- read_excel("Portfolio.xlsx", sheet="portfolio1")

# clear empty cells in my_data; overwrite it
my_portfolio <- na.omit(my_portfolio)
my_portfolio$Ticker <- sub("NASDAQ:", "", my_portfolio$Ticker)
my_portfolio$Ticker <- sub("NYSE:", "", my_portfolio$Ticker)

test_ticker <- my_portfolio$Ticker

```

```{r Portfolio - read from list}

#NASDAQ:TXN ---> TXN in yahoo finance
#NYSE:PG ---> PG...



test_ticker <- c('KO','PG')
#test_ticker <- c('KO','PG','JNJ','PFE','INTC','MMM','MCD','TXN','XOM','BLK','TROW','MRK','MO','O','AMT','VFC')
# test_ticker <- c('JNJ','ABT','PG','VFC','BLK','ABBV','T','VZ','SWK','TROW','MRK','PFE','INTC','MMM','MCD','BMY','EPD','RIO','NKE','CAT','WBA','tak','mc.pa','t.to','tyo.4502','CL') 


my_commodities <- c('GC=F','CL=F')
my_index <- c('^GSPC','^DJI','^GDAXI','^N225','^IXIC','^FTSE','^N100','^IBEX')

```

```{r Data query - yfr & quantmod & quandl & PriceR}



initial_date="2000-01-01" #year(initial_date)
ending_date = today()     #IMPORTANT: Historical inflation data on the current year might be unavailable



#ending_date="2023-01-14"
ending_date="2021-12-31" 



##### tabpanel -> Stock Analysis ##### 
      df_historical <- yf_get(tickers = test_ticker,          ### yfr ###
                              #last_date= Sys.Date()-1,
                              first_date= initial_date,
                              last_date= ending_date,
                              thresh_bad_data = 0.2,
                              freq_data="monthly") %>% select(ticker, price_close, ref_date)


        df_historical$ref_date_year = year(df_historical$ref_date)
      
##### tabpanel -> Dividend Analysis ##### 

      divs <- getDividends(test_ticker[1],                   ### QuandMod ###
                   from = initial_date,
                   to = ending_date, 
                   src = "yahoo", 
                   auto.assign = TRUE, 
                   auto.update = TRUE, 
                   verbose = FALSE)
      
      
      divs <- data.frame(date=index(divs), coredata(divs))
      colnames(divs) <- c('date','div')
      
      
      ### Divs Evolution ###
      
      divs$ticker <- rep(test_ticker[1],nrow(divs))
      
      
      for(i in 2:length(test_ticker)) {
      
        aux <- getDividends(test_ticker[i], 
                   from = initial_date,
                   to = ending_date, 
                   src = "yahoo", 
                   auto.assign = TRUE, 
                   auto.update = TRUE, 
                   verbose = FALSE)
      
      
      aux <- data.frame(date=index(aux), coredata(aux))
      colnames(aux) <- c('date','div')
      
      aux$ticker <- rep(test_ticker[i],nrow(aux))
      
      #append
      divs <- rbind(divs, aux)
       
      }
      
      
      ### GROUP BY YEAR & ticker
      
      divs_agg <- setNames( aggregate(div ~ year(date) + ticker, data = divs, FUN = sum, na.rm = TRUE),
                          c("Year_div","ticker","div"))
      
      
      ### Historical yield evolution
      
              # historical splits
              hist_splits <- quantmod::getSplits(test_ticker[1])
              hist_splits <- data.frame(date=index(hist_splits), coredata(hist_splits))
              colnames(hist_splits) <- c('ref_date','split')
              hist_splits$ticker <- rep(test_ticker[1],nrow(hist_splits))
              
              hist_splits =  hist_splits %>% arrange(desc(ref_date))
                    hist_splits =  transform(
                          hist_splits,
                        split_c = cumprod(c(na.omit(split)))
                      )
        
              for(i in 2:length(test_ticker)) {
                
                  aux <- quantmod::getSplits(test_ticker[i])
                  aux <- data.frame(date=index(aux), coredata(aux))
                  
                colnames(aux) <- c('ref_date','split')
                aux$ticker <- rep(test_ticker[i],nrow(aux))
                
                
                aux =  aux %>% arrange(desc(ref_date))
                aux =  transform(
                      aux,
                    split_c = cumprod(c(na.omit(split)))
                  )
                
                #append
                hist_splits <- rbind(hist_splits, aux)
              }
              
        hist_splits$ym <- format(as.Date(hist_splits$ref_date), "%Y-%m")
      
        colnames(divs) <- c('ref_date','div','ticker')      
        divs$ym <- format(as.Date(divs$ref_date), "%Y-%m")
        df_historical$ym <- format(as.Date(df_historical$ref_date), "%Y-%m")
        
        #join the DF's
        df_hist_yield = left_join(df_historical, divs, by=c('ym','ticker')) 
        df_hist_yield = left_join(df_hist_yield, hist_splits, by=c('ym','ticker')) 
        
        
        for(i in 1:length(test_ticker)) {
        
          df_hist_yield[df_hist_yield$ticker== test_ticker[i],] =  fill(df_hist_yield[df_hist_yield$ticker== test_ticker[i],] , div, .direction = 'down')
          
          df_hist_yield[df_hist_yield$ticker== test_ticker[i],] =  fill(df_hist_yield[df_hist_yield$ticker== test_ticker[i],] , split_c, .direction = 'up')
        
        }
        
        
        df_hist_yield$div_yield <- 4*100*df_hist_yield$div/df_hist_yield$price_close
        df_hist_yield$split_c = df_hist_yield$split_c %>% replace_na(1)
        df_hist_yield$yield_corrected <- df_hist_yield$div_yield/df_hist_yield$split_c ### end historical yield evolution
              

        
      ### Quandl data - (API needed)
      df1_quandl <- Quandl.datatable('SHARADAR/SF1',
                               ticker=test_ticker, 
                               calendardate.gte='2000-12-31',
                              qopts.columns=c('ticker' ,'debt','assets','calendardate','payoutratio','grossmargin','ebitdamargin','ev','evebit','evebitda','pe','assetturnover','eps','fcf','netmargin','roa','roe','roic','ros'), paginate = TRUE)

        df1_quandl$payoutratio = df1_quandl$dps/df1_quandl$eps
        df1_quandl$debt_assets = df1_quandl$debt/df1_quandl$assets

        

##### tabpanel -> Portfolio Analysis ##### 
      
        
        
        
#inflation & money input (priceR)
        
Year <- (year(initial_date)-1):(year(ending_date)-1) 
nominal_prices <- rep(1,length(Year))

df_inflation <- data.frame(Year, nominal_prices)
df_inflation$in_202x_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = (year(ending_date)-2)) ###PriceR###


df_inflation <- mutate(df_inflation,
                         yearly_inflation = 100*( lag(in_202x_dollars_factor)/in_202x_dollars_factor -1)
                            )%>% drop_na()
        
df_inflation[nrow(df_inflation) + 1,] <- c(2023, 1,0.95,1)    



df_inflation <- mutate(df_inflation, inflation_level = ( lag(in_202x_dollars_factor)/in_202x_dollars_factor -1)*100 )

        

##### tabpanel -> Indexes ##### 

       my_index <- c('^GSPC','^DJI','^GDAXI','^N225','^IXIC','^FTSE','^N100','^IBEX')
        
      # fetch data
      df_index <- yf_get(tickers = my_index, 
                           first_date = initial_date,
                           last_date = ending_date,
                           freq_data = "weekly") %>% 
           select('ticker','ref_date','price_close') 

      colnames(df_index) <- c('index','ref_date','price_index')
      
      

##### tabpanel -> Commodities ##### 

      my_commodities <- c('GC=F','CL=F')
      # fetch data
      df_commodity <- yf_get(tickers = my_commodities, 
                           first_date = initial_date,
                           last_date = ending_date,
                           freq_data = "weekly",
                           thresh_bad_data = 0.55) %>% 
                     select('ticker','ref_date','price_close')
      
      
      colnames(df_commodity) <- c('commodity','ref_date','price_com')
      
      
      df_index_com <- merge(df_index, df_commodity, by = "ref_date") 
      df_index_com$KPI <- df_index_com$price_index/df_index_com$price_com
      df_index_com$Ratio <-paste(df_index_com$index,df_index_com$commodity,sep="/")
               
               
               
##### tabpanel -> Currencies #####                
               
      # exc_rate <- historical_exchange_rates("USD", to = "PLN",
      #                                     start_date = "2000-01-10",
      #                                     end_date = "2022-11-30")
      # 
      # 
      # colnames(exc_rate)[which(names(exc_rate) == "date")] <- "ref_date"
      # colnames(exc_rate)[2] <- "ratio"
      
      
      
##### tabpanel -> Inflation ##### 
      
      
```


```{r dashboard interactive v 1.6}

#min_year = 1962
#max_year = 2022

min_year = year(initial_date)
max_year = year(ending_date)


#library(rstudio/shiny)

## Only run this example in interactive R sessions

if (interactive()) {

  shinyApp(
    
    ui = fluidPage(


   titlePanel(h1("R Stocks", align = "center")),

   tabsetPanel(               
           tabPanel("Stocks Analysis", 
                     sidebarLayout(
               sidebarPanel(width = 3, 
                         
                            sliderInput("years_stocks",
                                        label = h3("Years"),
                                        min = min_year, max = max_year, value = c(2000, 2020)),
                            selectInput(
                                        'selected_tickers',
                                        'Tickers',
                                        test_ticker,
                                        selected = c('PG','JNJ'),
                                        multiple = TRUE,
                                        selectize = TRUE,
                                        width = NULL,
                                        size = NULL
                                      ),
                           ),

               mainPanel(
                       fluidRow(
                            column(12,
                            
                              h1('yfR', align = "center"),
                               br(),
                              plotlyOutput("Stocks_evolution"),
                              br(),
                              h1('Quandl (API key required)', align = "center"),
                             br(),
                              plotlyOutput("Company_Info_ROS"),
                             br(),
                              plotlyOutput("Company_Info_ROA"),
                             br(),
                              plotlyOutput("Company_Info_ROIC"),
                             br(),
                              plotlyOutput("Company_Info_FCF"),
                             br(),
                              plotlyOutput("Company_Info_NetMargin")
                                )
                              )
                      ) #end main panel (stock analysis)
           ) #end sidebarLayout (stock analysis)
                    
                    ), #tab panel end stock analysis###
           
           tabPanel("Dividends Analysis",
             sidebarLayout(
               sidebarPanel(width = 3, 
                         
                           
                            sliderInput("years_divs",
                                        label = h3("Years"),
                                        min = min_year, max = max_year, value = c(2000, 2022)),
                            selectInput(
                                        'selected_tickers_div',
                                        'Tickers',
                                        test_ticker,
                                        selected = c('PG','JNJ'),
                                        multiple = TRUE,
                                        selectize = TRUE,
                                        width = NULL,
                                        size = NULL
                                      ),
                             sliderInput("n_years",
                                "Check n-y Dividend Growth",
                                min = 1, max = 10, value = 5,width = "90%"),
                           ),

               mainPanel(
                       fluidRow(
                            column(12,
                              h1('QuantMod', align = "center"),
                              br(),
                              plotlyOutput("Dividend_evolution"),
                              br(),
                              plotlyOutput("Dividend_n_growth"),
                              br(),
                              plotlyOutput("Dividend_n_growth_distrib"),
                              br(),
                              h1('QuantMod & yfR', align = "center"),
                              br(),
                              plotlyOutput("Hist_yield_evolution"),
                              br(),
                              plotlyOutput("Hist_yield_box"),
                              br(),
                              br(),
                              h1('Quandl (API key required)', align = "center"),
                              br(),
                              plotlyOutput("Company_Info1"),
                              br(),
                              plotlyOutput("Company_Info2"),
                              br(),
                              plotlyOutput("Company_Info3"),
                              br(),
                              plotlyOutput("Company_Info4"),
                              br(),
                              plotlyOutput("Company_Info5"),
                              br(),
                                )
                              )
                      ) #end main panel (dividend analysis)
           )
       ), #dividend analysis tab panel end ###
         tabPanel("Portfolio Analysis", 
                     sidebarLayout(
               sidebarPanel(width = 3, 
                         
                            sliderInput("years_portf",
                                        label = h3("Years investing"),
                                        min = min_year, max = max_year-1, value = c(2010, 2020)),
                            sliderInput("year_yoc",
                                "YoC looking from the year (TODAY*)",
                                min = min_year, max = max_year-1, value = 2021,width = "90%"),
                            sliderInput("money_in_portf",
                                "Monetary input - Monthly (value of 2021)",
                                min = 100, max = 5000, value = 1000,width = "90%"),
                            selectInput(
                                        'selected_tickers_portf',
                                        'Tickers',
                                        test_ticker,
                                        selected = c('KO','PG','JNJ','PFE'),
                                        multiple = TRUE,
                                        selectize = TRUE,
                                        width = NULL,
                                        size = NULL
                                      ),
                            checkboxInput("yearly_dca", "Yearly DCA instead of Full Period", FALSE),

                            
                            
                           ),

               mainPanel(
                       fluidRow(
                            column(12,
                              h1('Cash flow analysis - No dividend re-investment', align = "center"),
                                br(),
                                br(),
                              plotlyOutput("YoC"),
                                br(),
                              plotlyOutput('Div_CF'),
                                br(),
                              plotlyOutput('Stocks_bought'),
                                br(),
                              plotlyOutput('YoC_hist'),
                                br(),
                              plotlyOutput('CF_hist'),
                                br(),
                              DTOutput('DCA_DF'),
                              #DTOutput('DCA_DF_v2'),
                              #DTOutput('DCA_DF_v3'),
                              plotlyOutput('DCA_Portfolio'),
                              ##add capital gain over years
                                )
                              )
                      ) #end main panel (currencies)
           ) #end sidebarLayout (currencies)
     
                 ), #end tab panel end (Portfolio Analysis)
       #consider a TAB for dividend RE-INVEsTING
       tabPanel("Indexes", 
            sidebarLayout(
               sidebarPanel(width = 3, 
                         
                            sliderInput("years_indexes",
                                        label = h3("Years"),
                                        min = min_year, max = max_year, value = c(2000, 2022)),
                            selectInput(
                                        'selected_indexes',
                                        'Select Indexes',
                                        my_index,
                                        selected = c('^GSPC'),
                                        multiple = TRUE,
                                        selectize = TRUE,
                                        width = NULL,
                                        size = NULL
                                      ),
                           ),

               mainPanel(
                       fluidRow(
                            column(12,
                              h1('Indexes', align = "center"),
                              plotlyOutput("Index_Evolution"),
                                )
                              )
                      ) #end main panel (indexes)
           ) #end sidebarLayout (indexes)
                 ), #tab panel end (indexes)
       tabPanel("Commodities", 
            sidebarLayout(
               sidebarPanel(width = 3, 
                         
                            sliderInput("years_com",
                                        label = h3("Years"),
                                        min = min_year, max = max_year, value = c(2000, 2022)),
                            selectInput(
                                        'selected_com',
                                        'Select Commodities',
                                        my_commodities,
                                        selected = c('GC=F'),
                                        multiple = TRUE,
                                        selectize = TRUE,
                                        width = NULL,
                                        size = NULL
                                      ),
                            selectInput(
                                        'selected_ind',
                                        'Select Indexes',
                                        my_index,
                                        selected = c('^GSPC'),
                                        multiple = TRUE,
                                        selectize = TRUE,
                                        width = NULL,
                                        size = NULL
                                      ),
                           ),

               mainPanel(
                       fluidRow(
                            column(12,
                              h1('Commodities', align = "center"),
                              plotlyOutput("Index_Commodity"),
                                )
                              )
                      ) #end main panel (Commodities)
           ) #end sidebarLayout (Commodities)
                 ), #tab panel end (Commodities)
       tabPanel("Currencies", 
                     sidebarLayout(
               sidebarPanel(width = 3, 
                         
                            sliderInput("years_curr",
                                        label = h3("Years"),
                                        min = min_year, max = max_year, value = c(2000, 2022)),
                            selectInput(
                                        'FIAT1',
                                        'From FIAT',
                                        c('USD','EUR','PLN'),
                                        selected = 'USD',
                                        multiple = FALSE,
                                        selectize = TRUE
                                      ),
                            selectInput(
                                        'FIAT2',
                                        'To FIAT',
                                        c('USD','EUR','PLN'),
                                        selected = 'EUR',
                                        multiple = FALSE,
                                        selectize = TRUE
                                      ),
                           ),

               mainPanel(
                       fluidRow(
                            column(12,
                              h1('PriceR', align = "center"),
                              plotlyOutput("Exchange_Rates"),
                                )
                              )
                      ) #end main panel (currencies)
           ) #end sidebarLayout (currencies)
     
                 ), #tab panel end (currencies)
        tabPanel("Inflation", 
            sidebarLayout(
               sidebarPanel(width = 3, 
                         
                            sliderInput("years_inflation",
                                        label = h3("Years"),
                                        min = min_year, max = max_year-1, value = c(2000, 2021)),
                            selectInput(
                                        'selected_countries',
                                        'Select Countries',
                                        c('US'),
                                        selected = c('US'),
                                        multiple = TRUE,
                                        selectize = TRUE,
                                        width = NULL,
                                        size = NULL
                                      ),
                           ),

               mainPanel(
                       fluidRow(
                            column(12,
                              h1('Inflation', align = "center"),
                              plotlyOutput("Inflation_Evolution"),
                                )
                              )
                      ) #end main panel (Inflation)
           ) #end sidebarLayout (Inflation)
                 ) #tab panel end (Inflation)
                 
   )
), #ui, fluidpage
    
    
    
    
    server = function(input, output) {
                                      
      
##### tabpanel -> Stock Analysis ##### 
        ### Dataframes ###
      
          df_historical_interactive <- reactive ({
                 
                     return(          
                        filter(df_historical[df_historical$ticker %in% input$selected_tickers ,],
                               year(ref_date) >= input$years_stocks[1] &
                               year(ref_date) <= input$years_stocks[2])
                           )
           })
          
           quandl_df_interactive_1  <- reactive ({

               df1_quandl =  df1_quandl[df1_quandl$ticker %in% input$selected_tickers ,]
                  
                return( 
                 df1_quandl  %>% filter( year(df1_quandl$calendardate) >= input$years_divs[1] &
                                 year(df1_quandl$calendardate) <= input$years_divs[2])
                        )
         
           })
      
        ### GRAPHS ###
        output$Stocks_evolution <-renderPlotly({
                        plot_ly(df_historical_interactive(), type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~ref_date, y = ~price_close, name = ~ticker) %>%
            layout(title = '<b>Stocks Price Evolution<b>', xaxis = list(title = 'Date'), 
         yaxis = list(title = 'Price ($)'), legend = list(title=list(text='<b> Tickers </b>')))
        })
        
       output$Company_Info_ROS <-renderPlotly({
                       
                      plot_ly(quandl_df_interactive_1(), type = 'scatter', mode = 'lines')%>%
                                          add_trace(x = ~calendardate, y = ~ros*100, name = ~ticker)%>%
                    layout(title = '<b>Return on Sales Evolution<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'ROS (%)'), legend = list(title=list(text='<b> Tickers </b>')))
        })
       
       output$Company_Info_ROS <-renderPlotly({
                       
                      plot_ly(quandl_df_interactive_1(), type = 'scatter', mode = 'lines')%>%
                                          add_trace(x = ~calendardate, y = ~ros*100, name = ~ticker)%>%
                    layout(title = '<b>Return on Sales Evolution<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'ROS (%)'), legend = list(title=list(text='<b> Tickers </b>')))
        })     

       output$Company_Info_ROA <-renderPlotly({
                       
                      plot_ly(quandl_df_interactive_1(), type = 'scatter', mode = 'lines')%>%
                                          add_trace(x = ~calendardate, y = ~roa*100, name = ~ticker)%>%
                    layout(title = '<b>Return on Assets Evolution<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'ROA (%)'), legend = list(title=list(text='<b> Tickers </b>')))
        })                
       
       output$Company_Info_ROIC <-renderPlotly({
                       
                      plot_ly(quandl_df_interactive_1(), type = 'scatter', mode = 'lines')%>%
                                          add_trace(x = ~calendardate, y = ~roic*100, name = ~ticker) %>%
                    layout(title = '<b>Return on Invested Capital Evolution<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'ROIC (%)'), legend = list(title=list(text='<b> Tickers </b>')))
        })    
       
              output$Company_Info_FCF <-renderPlotly({
                       
                      plot_ly(quandl_df_interactive_1(), type = 'scatter', mode = 'lines')%>%
                                          add_trace(x = ~calendardate, y = ~fcf*100, name = ~ticker)%>%
                    layout(title = '<b>Free Cash Flow Evolution<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'FCF ($)'), legend = list(title=list(text='<b> Tickers </b>')))
        })    

       output$Company_Info_NetMargin <-renderPlotly({
                       
                      plot_ly(quandl_df_interactive_1(), type = 'scatter', mode = 'lines')%>%
                                          add_trace(x = ~calendardate, y = ~netmargin*100, name = ~ticker) %>%
                    layout(title = '<b>Net Margin Evolution<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'Net Margin (%)'), legend = list(title=list(text='<b> Tickers </b>')))
        })                        
       

      
                                   
 ##### tabpanel -> Dividend Analysis #####                                    
  ### Dataframes ###
      
      divs_agg_interactive <- reactive ({
        
                                 
        return(          
                  filter(divs_agg[divs_agg$ticker %in% input$selected_tickers_div ,] ,
                         Year_div >= input$years_divs[1] &
                         Year_div <= input$years_divs[2])
                     )
      
      })
      
   
      
      growth_df_interactive  <- reactive ({
        
                                divs_agg = divs_agg_interactive()
                                
                                growth_df <- data.frame( #empty dataframe
                                                            year_growth = integer(),
                                                             Ticker = character(),
                                                             Growth_hist = double()) 
                               growth_hist=c()
                               #n=1 #dividend growth of year Z vs Z-n (anualized)
                               n=input$n_years
                                
                                unique(divs_agg$ticker)
                                
                                for ( j in 1:length(unique(divs_agg$ticker)) ) {
                                  
                                  divs_agg_ticker <- filter(divs_agg,ticker %in% unique(divs_agg$ticker)[j])
                                  
                                  
                                  growth_hist=c()
                                for(i in (n+1):nrow(divs_agg_ticker)) {
                                
                                
                                  growth_hist[i-n] = ( (divs_agg_ticker$div[i]/divs_agg_ticker$div[i-n])^(1/n) -1)*100
                                 
                                }
                                  
                                  
                                    
                                  growth_df <-  rbind(growth_df,
                                                      data.frame(year_growth=divs_agg_ticker$Year_div[- (1:n)], growth_hist) %>% mutate(Ticker = unique(divs_agg$ticker)[j]) 
                                                      )
                                  
                                }
                                
                                return(growth_df)
      
      })
      
      
       df_hist_yield_interactive <- reactive ({
        return(          
                  filter(df_hist_yield[df_hist_yield$ticker %in% input$selected_tickers_div ,] ,
                         year(ref_date.x) >= input$years_divs[1] &
                         year(ref_date.x) <= input$years_divs[2])
                     )
      })
      
      
        quandl_df_interactive  <- reactive ({

         df1_quandl =  df1_quandl[df1_quandl$ticker %in% input$selected_tickers_div ,]
            
          return( 
           df1_quandl  %>% filter( year(df1_quandl$calendardate) >= input$years_divs[1] &
                           year(df1_quandl$calendardate) <= input$years_divs[2])
                  )
        })

      ### GRAPHS ###
        
        
            output$Dividend_evolution <-renderPlotly({
               
                  
                                    plot_ly(
                                            data = divs_agg_interactive(),
                                            x = ~Year_div,
                                            y = ~div,
                                            type = "bar",
                                            name = ~ticker,
                                            color=~ticker
                                          )  %>%
            layout(title = '<b>Dividend Evolution<b>', xaxis = list(title = 'Date'), 
         yaxis = list(title = 'Dividend ($)'), legend = list(title=list(text='<b> Tickers </b>')))
                                    
             
                                            }) 
            
            
            output$Dividend_n_growth <-renderPlotly({

                                       # plot_ly(growth_df, type = 'scatter', mode = 'lines')%>%
                                       #        add_trace(x = ~year_growth, y = ~growth_hist, name = ~Ticker) %>%
                                       #        layout(title =sprintf("Dividend growth %s-y ", input$n_years))

              plot_ly(growth_df_interactive(), type = 'scatter', mode = 'lines')%>%
                                              add_trace(x = ~year_growth, y = ~growth_hist, name = ~Ticker) %>%
                                layout(title =sprintf("<b>Dividend Growth Evolution %s-y<b>", input$n_years), xaxis = list(title = 'Date'), 
                             yaxis = list(title = '% Growth Rate'), legend = list(title=list(text='<b> Tickers </b>')))

              
            })
            
            
              output$Dividend_n_growth_distrib <-renderPlotly({

                                    

              plot_ly(growth_df_interactive(), y=~growth_hist, type = 'box', name = ~Ticker) %>%
            layout(title =sprintf("<b>Dividend Growth %s-y Distribution<b>", input$n_years), xaxis = list(title = '<b> Tickers </b>'), 
         yaxis = list(title = '% Growth Rate'), legend = list(title=list(text='<b> Tickers </b>')))

              
            })
            
                  
            output$Hist_yield_evolution <-renderPlotly({
          
                          plot_ly(df_hist_yield_interactive(), type = 'scatter', mode = 'lines') %>%
                              add_trace(x = ~ym, y = ~yield_corrected, name = ~ticker)  %>%
            layout(title = paste('<b>Historical Yield Evolution<b> - Period ',input$years_divs[1], ' to ',input$years_divs[2],sep=""), xaxis = list(title = 'Date'), 
         yaxis = list(title = '% Yield'), legend = list(title=list(text='<b> Tickers </b>')))
                                            }) 
            
             output$Hist_yield_box <-renderPlotly({
               
                                      plot_ly(
                                              data = df_hist_yield_interactive(),
                                              y = ~yield_corrected,
                                              type = 'box',
                                              name = ~ticker,
                                              color=~ticker
                                            )  %>%
                                      layout(title = paste('<b>Historical Yield Distribution<b> - Period ',input$years_divs[1], ' to ',input$years_divs[2],sep=""), xaxis = list(title = 'Tickers'), 
                                   yaxis = list(title = '% Growth Rate'), legend = list(title=list(text='<b> Tickers </b>')))
                                            }) 
            
          
           output$Company_Info1 <-renderPlotly({

                        plot_ly(quandl_df_interactive(), type = 'scatter', mode = 'lines')%>%
                                                        add_trace(x = ~calendardate, y = ~100*payoutratio, name = ~ticker) %>%
            layout(title = '<b>Payout Ratio Evolution<b>', xaxis = list(title = 'Date'), 
         yaxis = list(title = 'Payout Ratio (%)'), legend = list(title=list(text='<b> Tickers </b>')))
            })
           
            output$Company_Info3 <-renderPlotly({

                      plot_ly(quandl_df_interactive(), type = 'scatter', mode = 'lines')%>%
                                          add_trace(x = ~calendardate, y = ~100*ebitdamargin, name = ~ticker) %>%
                    layout(title = '<b>EBITDA Margin Evolution<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'EBITDA Margin (%)'), legend = list(title=list(text='<b> Tickers </b>')))
            })
            
             output$Company_Info2 <-renderPlotly({

                       plot_ly(quandl_df_interactive(), type = 'scatter', mode = 'lines')%>%
                          add_trace(x = ~calendardate, y = ~100*grossmargin, name = ~ticker) %>%
                      layout(title = '<b>Gross Margin Evolution<b>', xaxis = list(title = 'Date'), 
                   yaxis = list(title = 'Gross Margin (%)'), legend = list(title=list(text='<b> Tickers </b>')))
            })
             
              output$Company_Info4 <-renderPlotly({

                        plot_ly(quandl_df_interactive(), type = 'scatter', mode = 'lines')%>%
                                  add_trace(x = ~calendardate, y = ~100*evebitda, name = ~ticker)%>%
                      layout(title = '<b>EV/EBITDA Evolution<b>', xaxis = list(title = 'Date'), 
                   yaxis = list(title = 'EV/EBITDA (%)'), legend = list(title=list(text='<b> Tickers </b>')))
            })
              
              
              
              
            output$Company_Info5 <-renderPlotly({
              plot_ly(quandl_df_interactive(), type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~100*debt_assets, name = ~ticker)  %>%
                    layout(
                      yaxis = list(
                        range=c(0,150)
                      )
                    ) %>%
                layout(title = '<b>Debt/Assets Evolution Evolution<b>', xaxis = list(title = 'Date'), 
             yaxis = list(title = 'Debt/Assets Evolution (%)'), legend = list(title=list(text='<b> Tickers </b>')))
            })
            
            
              
      ##### tabpanel -> Portfolio Analysis ##### 
             ### Dataframes ### 
            
            hist_price_infl_filtered_interactive <- reactive ({
               
              # df_inflation$money_input_infl <-input$money_in_portf/df_inflation$in_2020_dollars_factor
              #   df_inflation$money_input_infl_year <-  length(unique(input$selected_tickers_portf))*input$money_in_portf/df_inflation$in_2020_dollars_factor 
                
                
                
df_inflation$money_input_infl <-input$money_in_portf/length(unique(input$selected_tickers_portf))/df_inflation$in_202x_dollars_factor 
df_inflation$money_input_infl_year <- input$money_in_portf/df_inflation$in_202x_dollars_factor 
                
                
                df_historical$Year <- as.integer(format(as.Date(df_historical$ref_date), "%Y"))
                
                hist_price_infl <- left_join(df_historical, df_inflation, by=c('Year')) 
                hist_price_infl$Stocks <- hist_price_infl$money_input_infl/hist_price_infl$price_close          #no round down !!!!!!!!
                
                hist_price_infl_filtered = hist_price_infl[hist_price_infl$Year>= input$years_portf[1] &
                                       hist_price_infl$Year<= input$years_portf[2]  
                                       & hist_price_infl$ticker %in% input$selected_tickers_portf ,]      
                return(hist_price_infl_filtered)
              
            })
            
            
            DCA_df_interactive <- reactive ({
              
               DCA_df <- setNames(
                          aggregate(hist_price_infl_filtered_interactive()$Stocks,            
                        by=list(Category=hist_price_infl_filtered_interactive()$ticker),
                        FUN=sum),  # setNames function
                       c("ticker", "Stocks"))
                    
                     
       DCA_df$DCA <- (sum(hist_price_infl_filtered_interactive()$money_input_infl)/length(unique(input$selected_tickers_portf)))/DCA_df$Stocks
                                       
              
              return(DCA_df)
              
            })
            
            
            DCA_df_divs_interactive  <- reactive ({
                                            
        
        DCA_df_divs <- left_join(DCA_df_interactive(), divs_agg[divs_agg$Year_div== input$year_yoc,]%>% group_by(ticker), by=c('ticker'='ticker')) #join to latest values
        
        #DCA_df_divs <- left_join(DCA_df_divs, hist_price_infl_filtered %>% group_by(ticker) %>% top_n(1, ym), by=c('ticker'='ticker'))#join to latest values 
        
        
        DCA_df_divs$invested <- DCA_df_divs$Stocks*DCA_df_divs$DCA
        DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
        DCA_df_divs$YoC_Ticker <- ((DCA_df_divs$div_cash_flow)/(DCA_df_divs$invested)+1)*100-100 
        
            
          return( 
           DCA_df_divs 
                  )
        })
            
            

            
            dfz_interactive <-reactive({
              
              
            historical_yield <- list()
            historical_CF <- list()
            
            
             #for ( j in input$years_portf[1]:input$years_portf[2] ) {
              for ( j in input$years_portf[1]:input$year_yoc ) {
                   
                                                   
                DCA_df_divs <- left_join(DCA_df_interactive(), divs_agg %>% group_by(ticker) %>% filter( Year_div == j)  , by=c('ticker'='ticker')) 
                
                DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
                   
                
                historical_yield <- append(
                      historical_yield, 
                      (sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl_filtered_interactive()[hist_price_infl_filtered_interactive()$Year <= j ,]$money_input_infl)+1)*100-100
                )
                
                
                 historical_CF <- append(
                    historical_CF, 
                    sum(DCA_df_divs$div_cash_flow)
                  )
       
                   
             }
                  
              historical_yield =unlist(historical_yield)
              
              historical_CF =unlist(historical_CF)
              
              # yearz =  input$years_portf[1]:input$years_portf[2]
              yearz =  input$years_portf[1]:input$year_yoc
              
              dfz = data.frame(historical_yield,historical_CF,yearz)
              return(dfz)
              
            })
            
            
            DCA_Portfolio_DF <-reactive({
              
                       
                     aux <-   filter(df_historical[df_historical$ticker %in% input$selected_tickers_portf ,],
                               year(ref_date) >= input$years_portf[1] &
                               year(ref_date) <= input$years_portf[2]
                               )
                           
              
                      if(input$yearly_dca == TRUE){
                            DCA_Portfolio_DF <-  left_join(
                              aux %>%
                                                   dplyr::rename(Historical_Price = price_close),
                              aux[,c("ticker","price_close","ref_date_year")] %>%
                                                   group_by(ticker, ref_date_year) %>%
                                                   summarise_at(.vars = c("price_close"), .funs = mean) %>%
                                                   dplyr::rename(DCA = price_close),
                               by=c('ticker'='ticker', 'ref_date_year'='ref_date_year')
                              )
                      }else{
                        DCA_Portfolio_DF <-  left_join(
                              aux %>%
                                                   dplyr::rename(Historical_Price = price_close),
                              aux[,c("ticker","price_close","ref_date_year")] %>%
                                                   group_by(ticker) %>%
                                                   summarise_at(.vars = c("price_close"), .funs = mean) %>%
                                                   dplyr::rename(DCA = price_close),
                               by=c('ticker'='ticker')
                              )
                      }
                    
                    
                    DCA_Portfolio_DF$ticker_dca <- paste('DCA',DCA_Portfolio_DF$ticker)
                    
                    return(DCA_Portfolio_DF)
              
            })
            
            
            ### TABLES ###
            
            output$DCA_DF = renderDT(DCA_df_divs_interactive()
                                     )
            
          
            

            
            
            ### GRAPHS ###
            

              output$YoC <-renderPlotly({
                
    plot_ly( DCA_df_divs_interactive(), type = 'bar') %>%
      add_trace(x = ~ticker, y = ~YoC_Ticker, name = 'Portfolio YoC') %>%   
                    layout(title = paste("<b>YoC TODAY* per ticker<b> with last buy on ",input$years_portf[2]),
                           xaxis = list(title = 'Tickers'), 
                            yaxis = list(title = 'YoC (%)'), legend = list(title=list(text='<b> Tickers </b>')))
                       
              # layout(title = paste("YoC TODAY* per ticker with last buy on ",input$years_portf[2]))  %>%
                
                
                
                      })
              
              
                 output$Stocks_bought <- renderPlotly({
              
              
                     plot_ly(hist_price_infl_filtered_interactive(), type = 'bar')%>%
                                        add_trace(x = ~ym, y = ~Stocks, name = ~ticker)  %>%   
                    layout(title = "<b>Stocks Bought Over Time<b>",
                           xaxis = list(title = 'Date'), 
                            yaxis = list(title = 'Stocks Bought'), legend = list(title=list(text='<b> Tickers </b>')))
              
            })
            
            output$Div_CF <-renderPlotly({
                
    plot_ly(DCA_df_divs_interactive(), labels = ~ticker, values = ~div_cash_flow, type = 'pie')%>% 
                layout(title = '<b>Dividend Cash Flow split TODAY*</b>',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)
         )
            })
            
            
            
               output$YoC_hist <- renderPlotly({

                  ay <- list(
                    tickfont = list(color = "red"),
                    overlaying = "y",
                    side = "right",
                    title = "<b>$</b> invested")

                  plot_ly() %>%
                            add_trace(data= dfz_interactive(), x = ~yearz, y = ~historical_yield, name = "<b>Portfolio Historical Yield</b>", type = "bar") %>%
                            add_trace(data= aggregate(money_input_infl ~ Year, data = hist_price_infl_filtered_interactive(), FUN = sum), name="Monetary Input", x = ~Year, y = ~money_input_infl, yaxis = "y2", mode = "lines+markers", type = "scatter")  %>%
                            layout(
                                  title = "<b>Historical YoC of the Portfolio vs Monetary input<b>", yaxis2 = ay,
                                  xaxis = list(title="Year"),
                                  yaxis = list(title="YoC (%)")
                            )%>%
                           layout(plot_bgcolor='#e5ecf6',
                                xaxis = list(
                                  zerolinecolor = '#ffff',
                                  zerolinewidth = 2,
                                  gridcolor = 'ffff'),
                                yaxis = list(
                                  zerolinecolor = '#ffff',
                                  zerolinewidth = 2,
                                  gridcolor = 'ffff')
                            )
                 
               })
               
               
               
                output$CF_hist <- renderPlotly({

                 
            plot_ly() %>% 
                  add_trace(data= dfz_interactive(), x = ~yearz, y = ~historical_CF, name = "Portfolio CF", type = "bar") %>%
                    add_trace(data= dfz_interactive() %>% mutate(cum_div = cumsum(historical_CF)) 
                              , name="Cumulative Dividend", x = ~yearz, y = ~cum_div, mode = "lines+markers", type = "scatter") %>%
                  add_trace(data= aggregate(money_input_infl ~ Year, data = hist_price_infl_filtered_interactive(), FUN = sum), name="Monetary Input", x = ~Year, y = ~money_input_infl, mode = "lines+markers", type = "scatter") %>%   
                     add_trace(data= aggregate(money_input_infl ~ Year, data = hist_price_infl_filtered_interactive(), FUN = sum)  %>% mutate(cum_money_input = cumsum(money_input_infl)), name="Cumulative Monetary Input", x = ~Year, y = ~cum_money_input, mode = "lines+markers", type = "scatter") %>%   
                  layout(
                                  title = "<b>Historical CF vs Monetary Input<b>",
                                  xaxis = list(title="Year"),
                                  yaxis = list(title="Historical Cash Flow ($)")
                        )
        
                         
                 
               })
                
                
                output$DCA_Portfolio <- renderPlotly({

                  
          if(input$yearly_dca == TRUE){
                  
                   plot_ly( DCA_Portfolio_DF()  ) %>%
                      add_trace(x = ~ref_date, y = ~Historical_Price, type = 'scatter', mode = "lines", name = ~ticker)%>%
                    add_trace(x = ~ref_date, y = ~DCA, type = 'scatter', mode = "lines", name = ~ticker_dca)%>%
                                  layout(title = '<b> DCA (Yearly) <b>', xaxis = list(title = 'Date'),
                                           yaxis = list(title = 'Price ($)'), legend = list(title=list(text='<b> Ticker </b>')))
          }else{
            
            plot_ly( DCA_Portfolio_DF()  ) %>%
                      add_trace(x = ~ref_date, y = ~Historical_Price, type = 'scatter', mode = "lines", name = ~ticker)%>%
                    add_trace(x = ~ref_date, y = ~DCA, type = 'scatter', mode = "lines", name = ~ticker_dca)%>%
                                  layout(title = '<b> DCA (Full Period)<b>', xaxis = list(title = 'Date'),
                                           yaxis = list(title = 'Price ($)'), legend = list(title=list(text='<b> Ticker </b>')))
          }
         
               })
                
        ##### tabpanel -> Indexes ##### 
        ### Dataframes ###             
                
        df_indexinteractive <- reactive ({
                     return(          
                        filter(df_index[df_index$index %in% input$selected_indexes ,],
                               year(ref_date) >= input$years_indexes[1] &
                               year(ref_date) <= input$years_indexes[2])
                           )
           })
                  
                
                
        ### GRAPHS ###
               
        output$Index_Evolution <-renderPlotly({
                        
          
                 plot_ly(df_indexinteractive(), type = 'scatter', mode = 'lines') %>%
                         add_trace(x = ~ref_date, y = ~price_index, name = ~index) %>%
                         layout(title = '<b>Index Price Evolution <b>',
                              xaxis = list(title = 'Date'), 
                              yaxis = list(title = 'Price ($)'),
                              legend = list(title=list(text='<b> Index </b>')))
          
          
        })           
                 
                
                
        ##### tabpanel -> Commodities ##### 
        ### Dataframes ###
        
        df_index_com_interactive <- reactive ({
                 
                     return(          
                        filter(df_index_com[df_index_com$commodity %in% input$selected_com & df_index_com$index %in% input$selected_ind ,],
                               year(ref_date) >= input$years_com[1] &
                               year(ref_date) <= input$years_com[2])
                           )
           })
        
        ### GRAPHS ###
        output$Index_Commodity <-renderPlotly({
                        
          
                 plot_ly(df_index_com_interactive(), type = 'scatter', mode = 'lines') %>%
                         add_trace(x = ~ref_date, y = ~KPI, name = ~Ratio) %>%
                         layout(title = '<b>Index to Commodity Evolution <b>',
                              xaxis = list(title = 'Date'), 
                              yaxis = list(title = 'Ratio'),
                              legend = list(title=list(text='<b> Index / Commodity </b>')))
          
          
        })        
              
           
        ##### tabpanel -> Currencies ##### 
        ### Dataframes ###
      
          exc_rate_interactive <- reactive ({
                 
                  exc_rate <- historical_exchange_rates(input$FIAT1, to = input$FIAT2,
                                                      start_date = "2000-01-10",
                                                      end_date = "2022-11-30")
            
                  colnames(exc_rate)[which(names(exc_rate) == "date")] <- "ref_date"
                  colnames(exc_rate)[2] <- "ratio"
            
                     return(          
                        filter(exc_rate,
                               year(ref_date) >= input$years_curr[1] &
                               year(ref_date) <= input$years_curr[2])
                           )
           })
      
        ### GRAPHS ###
        output$Exchange_Rates <-renderPlotly({
                        plot_ly(
                            data = exc_rate_interactive(),
                            x = ~ref_date,
                            y = ~ratio,
                            type = "scatter",
                            mode='lines')  %>%
                         layout(title = '<b> Exchange Rate <b>',
                              xaxis = list(title = 'Date'), 
                              yaxis = list(title = 'Ratio'),
                              legend = list(title=list(text='<b> Currency Pair </b>')))
        })
        
        
        
        
        ##### tabpanel -> Inflation ##### 
        ### Dataframes ###             
                
        df_inflationinteractive <- reactive ({
                     return(          
                        filter(df_inflation,
                               Year >= input$years_inflation[1] &
                               Year <= input$years_inflation[2])
                           )
           })
                  
                
                
        ### GRAPHS ###
               
        output$Inflation_Evolution <-renderPlotly({
                        
          
          # plot_ly(df_inflation) %>%
          # add_trace(x = ~Year, y = ~in_202x_dollars_factor, type = 'scatter', mode = "lines", yaxis = "y2",name="$ Factor Y2021") %>%
          #   add_trace(x = ~Year, y = ~inflation_level, type = 'bar',name='Yearly Inflation US')%>%
          #           layout(title = '<b>US Inflation Data<b>', xaxis = list(title = 'Date'), 
          #                  yaxis = list(title = 'Inflation (%Y)'), legend = list(title=list(text='<b> Legend </b>')),
          #                  yaxis2 = list(overlaying = "y", side = "right",automargin = T,title = "Factor Y2021",range = c(0,3))
          #                 )
          # 
          

plot_ly(df_inflationinteractive(), type = 'scatter', mode = 'lines') %>%
      add_trace(x = ~Year, y = ~in_202x_dollars_factor, name="Inflation factor to Y2021") %>%
                    layout(title = '<b>US Historical Inflation<b>', xaxis = list(title = 'Year'), 
                           yaxis = list(title = 'a'),
                           legend = list(title=list(text='<b> Legend </b>')))  %>%
      add_trace(x = ~Year, y = ~inflation_level, name="Inflation Yearly (%)") %>%
                    layout(title = '<b>US Historical Inflation<b>', xaxis = list(title = 'Year'), 
                          yaxis = list(title = '(%)'), 
                          legend = list(title=list(text='<b> Legend </b>')))
          
          
        })  
        
        
        
        


                        } #server
  ) #shinyapp
  
  
} #if interactive

```