version: '3.8'

services:
  stock-app:
    image: ghcr.io/jalcocert/r-stocks:latest #r_stocks
    container_name: RStock_Container
    ports:
      - "3838:3838"
    volumes:
      - stock-data:/app
    # networks:                   #optional
    #   - cloudflare_tunnel       #optional
    restart: unless-stopped

# networks:             #optional
#   cloudflare_tunnel:  #optional
#     external: true    #optional

volumes:
  stock-data:
    name: stock_data_volume