---
title: "R_Stocks_Analysis"
author: "JAT"
output: html_document
date: '2022-12-02'
editor_options: 
  chunk_output_type: console
---




```{r Libraries needed - Installation}
#Required for the first use of the program in a device


# install.packages(c("rlang","devtools"), dependencies = TRUE)

#install.packages("BatchGetSymbols") #substituted for yfR
#devtools::install_github('msperlin/yfR') #yfR install option 1
#install.packages('yfR', dependencies = TRUE) #yfR install option 2
#install.packages("priceR", dependencies = TRUE) 
#install.packages("Quandl", dependencies = TRUE) #API key needed
#install.packages("quantmod", dependencies = TRUE) 
#install.packages("qmao", repos="http://R-Forge.R-project.org", dependencies = TRUE)

install.packages(c("tibble", "dplyr","writexl","shiny","shinythemes","shinyWidgets","scales","readxl","dtplyr","tidyverse","DT","ggthemes","plotly","plyr","leaflet","ggplot2","lubridate","reshape2"), dependencies = TRUE) 


```

```{r Libraries check}
#If needed for debugging



# pkg = tibble::tibble(
#   Package = names(installed.packages()[,3]),
#   Version = unname(installed.packages()[,3])
# )
# 
# 
# pkg_filtered=dplyr::filter(pkg, Package %in% c("tibble","yfR","priceR","Quandl","quantmod","qmao" "dplyr","shiny","shinythemes","shinyWidgets","scales","readxl","dtplyr","tidyverse","DT","ggthemes","plotly","plyr","leaflet","devtools","ggplot2","rlang"))

#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

#write.csv(pkg_filtered,paste(getwd(),"/pkgs_your_name.csv",sep=""), row.names = FALSE)


#packageVersion("rlang")
#"rlang" %in% loadedNamespaces()

```


```{r Load the libraries & Config file}


library("rstudioapi") #to manage the directory

#setwd('C:/Users')
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) #this Rmd file must be saved


library("yaml") 
vars = yaml.load_file("config.yml")
quandl_api = vars$config$quandl_api
#library('data.table')

#install.packages("pacman")
pacman::p_load(dplyr,dtplyr,shinythemes,shinyWidgets,readxl,scales,... = tidyverse,DT,ggthemes,ggplot2,plotly,plyr,leaflet,devtools,yaml,tidyr)

### Financial libraries ###

#library("BatchGetSymbols") #depricated --->yfR

library("yfR")      #historical stock valuation -> Instead of BatchGetSymbols
library("priceR")   #inflation / currency exchange ===> adjust_for_inflation
library("quantmod") #dividends (getDividends), metals price
library("Quandl")   #EPS, debt, assets (#API key needed)

############################


library(tidyr) #for drop_na

#library(tidyr)

library("qmao")     #quand mod add ons -> EPS
library("dplyr")
library("lubridate")
library("reshape2")





#setwd("C:/Users/your/windows/path")
getwd()



```


```{r quantmod - test}

df_splits <- quantmod::getSplits('PG')

quantmod::getSplits('LON.DRTY')

quantmod::getSplits('T.TO')

getSymbols("0941.hk")
getSymbols("mc.pa") #LVMH




quantmod::getSymbols('PG')

getSymbols.yahooj('TYO')


```

```{r Portfolio - read from excel}

# set as direction the one of .Rmd archive; .xlsx and .Rmd mut be on same folder
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
  
my_portfolio <- read_excel("Portfolio.xlsx", sheet="portfolio1")

# clear empty cells in my_data; overwrite it
my_portfolio <- na.omit(my_portfolio)

my_portfolio$Ticker <- sub("NASDAQ:", "", my_portfolio$Ticker)
my_portfolio$Ticker <- sub("NYSE:", "", my_portfolio$Ticker)

test_ticker <- my_portfolio$Ticker
```

```{r Portfolio - read from list}

#NASDAQ:TXN ---> TXN in yahoo finance
#NYSE:PG ---> PG...

test_ticker <- my_portfolio$Ticker
#test_ticker <- c('KO','PG','JNJ','PFE','INTC','MMM','MCD','TXN','XOM','BLK','TROW')

```

```{r test - quandl}
#https://github.com/quandl/quandl-r
#https://data.nasdaq.com/databases/SF1/documentation


# Get your API key from quandl.com and include it on a 'config.yaml' file
vars = yaml.load_file("config.yml")
quandl_api = vars$config$quandl_api
 
# Add the key to the Quandl keychain
Quandl.api_key(quandl_api)


Quandl.datatable('SHARADAR/SP500', action=c('added','removed'), date.gte='2015-01-01')

Quandl("NSE/KO")
Quandl("NSE/OIL")

df_quandl_crypto <- Quandl("BITFINEX/BTCUSD")
df0_quandl <- Quandl("WIKI/KO")



#df1_quandl <- Quandl.datatable('SHARADAR/SF1', ticker='AAPL')


df1_quandl <- Quandl.datatable('SHARADAR/SF1',
                               ticker=c('KO'),
                               calendardate.gte='2000-12-31',
                               )


df1_quandl <- Quandl.datatable('SHARADAR/SF1',
                               ticker=c('PG','TXN'),
                               calendardate.gte='2000-12-31',
                               )

df1_quandl <- Quandl.datatable('SHARADAR/SF1',                        ### quandl ###
                               ticker=c('INTC','TXN'), 
                               calendardate.gte='2000-12-31',
                               qopts.columns=c('ticker' ,'debt','assets','calendardate','payoutratio','grossmargin','ebitdamargin','ev','evebit','evebitda','pe','assetturnover','eps','fcf','netmargin','roa','roe','roic','ros'))


test_ticker <- sub("NASDAQ:", "", test_ticker)
test_ticker <- sub("NYSE:", "", test_ticker)


df1_quandl <- Quandl.datatable('SHARADAR/SF1',                        ### quandl ###
                               ticker=test_ticker, 
                               calendardate.gte='2000-12-31',
                               qopts.columns=c('ticker' ,'debt','assets','calendardate','payoutratio','grossmargin','ebitdamargin','ev','evebit','evebitda','pe','assetturnover','eps','fcf','netmargin','roa','roe','roic','ros'), paginate = TRUE)





#df1_quandl <- Quandl.datatable("SHARADAR/SF1", paginate = TRUE) #eps #dps #gross_margin #div_yield #debt #assets #ebitda #ev #ebitdamargin #...

# test_ticker <- sub("NASDAQ:", "", test_ticker)
# test_ticker <- sub("NYSE:", "", test_ticker)
# 
# df1_quandl <- filter(df1_quandl[df1_quandl$ticker %in% test_ticker ,])


df1_quandl$payoutratio = df1_quandl$dps/df1_quandl$eps
df1_quandl$debt_assets = df1_quandl$debt/df1_quandl$assets




plot_ly(df1_quandl, type = 'scatter', mode = 'lines') %>%
      add_trace(x = ~calendardate, y = ~ros*100, name='ROS') %>%
                    layout(title = '<b>Return on Sales<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'ROS (%)'), legend = list(title=list(text='<b> Date </b>')))


plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~ros, name = ~ticker)%>%
        layout(title = 'ROS')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~roic, name = ~ticker)%>%
        layout(title = 'roic')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~roa*100, name = ~ticker)%>%
        layout(title = 'roa')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~netmargin, name = ~ticker)%>%
        layout(title = 'netmargin')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~fcf, name = ~ticker)%>%
        layout(title = 'Free Cash Flow - FCF')


plot_ly(df1_quandl, type = 'bar')%>%
                    add_trace(x = ~calendardate, y = ~fcf, name = ~ticker )%>%
                    layout(title = '<b>Free Cash Flow - FCF<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'FCF ($)'), legend = list(title=list(text='<b> Date </b>')))


# plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
#                     add_trace(x = ~calendardate, y = ~eps, name = ~ticker)%>%
#         layout(title = 'Earning per Share - EPS')


plot_ly(df1_quandl, type = 'bar')%>%
                    add_trace(x = ~calendardate, y = ~eps, name = ~ticker) %>%
                    layout(title = '<b>Earning per Share - EPS<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'EPS ($)'), legend = list(title=list(text='<b> Ticker </b>')))


plot_ly(df1_quandl, x = ~calendardate, y = ~eps, type = "bar", name = ~ticker) %>%
    add_trace(x = ~calendardate, y = ~netmargin*100, type = 'scatter', mode = "lines", yaxis = "y2", name = ~ticker) %>%
    layout(yaxis2 = list(overlaying = "y", side = "right"))


plot_ly(df1_quandl, x = ~calendardate, y = ~eps, type = "bar", name = ~ticker) %>%
    add_trace(x = ~calendardate, y = ~netmargin*100, type = 'scatter', mode = "lines", yaxis = "y2", name = ~ticker)%>%
                    layout(title = '<b>Earning per Share and Net Margin<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'EPS ($)'), legend = list(title=list(text='<b> Ticker </b>')),
                yaxis2 = list(overlaying = "y", side = "right",automargin = T,title = "Net Margin"))

plot_ly(df1_quandl, name = ~ticker) %>%
    add_trace(x = ~calendardate, y = ~netmargin*100, type = 'scatter', mode = "lines", yaxis = "y2")%>%
      add_trace(x = ~calendardate, y = ~eps, type = 'bar')%>%
                    layout(title = '<b>Earning per Share and Net Margin<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'EPS ($)'), legend = list(title=list(text='<b> Ticker </b>')),
                yaxis2 = list(overlaying = "y", side = "right",automargin = T,title = "Net Margin (%)"))

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~assetturnover, name = ~ticker)%>%
        layout(title = 'assetturnover')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~assetturnover, name = ~ticker)%>%
        layout(title = 'assetturnover')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~assetturnover, name = ~ticker)%>%
        layout(title = 'assetturnover')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~pe, name = ~ticker)%>%
        layout(title = 'PE')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~100*divyield, name = ~ticker)%>%
        layout(title = 'div yield')


plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~100*payoutratio, name = ~ticker)%>%
        layout(title = 'Payout Ratio Evolution')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~100*ebitdamargin, name = ~ticker)%>%
         layout(title = 'EBITDA Margin Evolution')
   

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~100*grossmargin, name = ~ticker)%>%
         layout(title = 'Gross Margin Evolution')

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~100*evebitda, name = ~ticker)%>%
         layout(title = 'EV/EBITDA Evolution')
    
  
plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~100*debt_assets, name = ~ticker)  %>%
  layout(
    yaxis = list(
      range=c(0,150)
    )
  ) %>%
        layout(title = 'Debt/Assets Evolution')


### ROE Estimation with ROA + Debt/Assets Ratio

plot_ly(df1_quandl, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~calendardate, y = ~roa/(1-debt_assets)*100, name = ~ticker)%>%
        layout(title = 'ROE')


  
#df1b_quandl <- Quandl.datatable("SHARADAR/SF1", ticker="AAPL", paginate = TRUE) 
  df1c_quandl <-  Quandl.datatable("SHARADAR/SF1",
                               ticker=c('NKE','PG','O','ABT','CAT','PEP','KO','LEG','VFC','AMT','MO','BLK','CAT','ABBV','T','VZ','SWK','TROW','MRK','PFE','INTC','MMM','MCD','BMY'),
                                   paginate = TRUE) 
  
df1c_quandl$payoutratio = df1c_quandl$dps/df1c_quandl$eps
df1c_quandl$debt_assets = df1c_quandl$debt/df1c_quandl$assets
  

      
plot_ly(df_hist_yield,y = ~yield_corrected, type = "box",name=~ticker)

  ggplotly(
  ggplot(df1c_quandl, aes(x=calendardate, y=100*divyield, group=ticker)) + geom_line(aes(colour = ticker))
  )
  
    ggplotly(
  ggplot(df1c_quandl, aes(x=calendardate, y=100*ebitdamargin, group=ticker)) + geom_line(aes(colour = ticker))
  ) %>%
        layout(title = 'EBITDA Margin Evolution')
    
    
    ggplotly(
  ggplot(df1c_quandl, aes(x=calendardate, y=100*grossmargin, group=ticker)) + geom_line(aes(colour = ticker))
  )  %>%
        layout(title = 'Gross Margin Evolution')

  ggplotly(
  ggplot(df1c_quandl, aes(x=calendardate, y=100*payoutratio, group=ticker)) + geom_line(aes(colour = ticker))
  )  %>%
  layout(
    yaxis = list(
      range=c(0,300)
    )
  )%>%
        layout(title = 'Payout Ratio Evolution')
  
  ggplotly(
  ggplot(df1c_quandl, aes(x=calendardate, y=100*debt_assets, group=ticker)) + geom_line(aes(colour = ticker))
  )  %>%
  layout(
    yaxis = list(
      range=c(0,150)
    )
  ) %>%
        layout(title = 'Debt/Assets Evolution')


df2_quandl <- Quandl("WIKI/PG",collapse='annual')

df3_quandl = Quandl.datatable("ZACKS/FC", ticker=c("AAPL", "MSFT"), per_end_date.gt="2015-01-01", qopts.columns=c("m_ticker", "per_end_date", "tot_revnu"))

df4_quandl = Quandl.datatable("ZACKS/FC", ticker="AAPL")

```


```{r test - yfR}
#https://docs.ropensci.org/yfR/articles/diff-batchgetsymbols.html

#BatchGetSymbols::BatchGetSymbols is now yfR::yf_get()


#yfR::yf_collection_get("SP500")

first_date <- Sys.Date() - 4
last_date <- Sys.Date()

df_collection <- yf_collection_get("SP500",
                                   first_date = first_date,
                                    last_date = last_date)

unique(df_collection$ticker)

#which(df_collection$ticker == 'INTC', arr.ind=TRUE)

```


```{r sp500 vs gold -  commodities - yfR - interactive ready}



# set options for algorithm


my_index <- c('^GSPC','^GDAXI')
first_date <- Sys.Date() - 100
last_date <- Sys.Date()

# fetch data
df_index <- yf_get(tickers = my_index, 
                     first_date = first_date,
                     last_date = last_date,
                     freq_data = "weekly") %>% 
           select('ticker','ref_date','price_close') 

colnames(df_index) <- c('index','ref_date','price_index')


#my_ticker <- c('GC=F')
my_commodities <- c('GC=F','CL=F')
# fetch data
df_commodity <- yf_get(tickers = my_commodities, 
                     first_date = first_date,
                     last_date = last_date,
                     freq_data = "weekly",
                     thresh_bad_data = 0.55) %>% 
               select('ticker','ref_date','price_close')


colnames(df_commodity) <- c('commodity','ref_date','price_com')


df_index_com <- merge(df_index, df_commodity, by = "ref_date") 
df_index_com$KPI <- df_index_com$price_index/df_index_com$price_com
df_index_com$Ratio <-paste(df_index_com$index,df_index_com$commodity,sep="/")
        
# 
#         plot_ly(df_index_com, type = 'scatter', mode = 'lines') %>%
#       add_trace(x = ~ref_date, y = ~KPI, name = 'SP/Gold') %>%
#                     layout(title = '<b>Index to Gold Evolution (one ticker - one com<b>', xaxis = list(title = 'Date'), 
#                  yaxis = list(title = 'Ratio'), legend = list(title=list(text='<b> Index / Commodity </b>')))
        
        
        

        plot_ly(df_index_com, type = 'scatter', mode = 'lines') %>%
      add_trace(x = ~ref_date, y = ~KPI, name = ~Ratio) %>%
                    layout(title = '<b>Index to Gold Evolution - Multiple<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'Ratio'), legend = list(title=list(text='<b> Index / Commodity </b>')))
        
        
        

```

```{r indexes - yfR - interactive ready}

#https://finance.yahoo.com/world-indices


# set options for algorithm


my_index <- c('^GSPC','^DJI','^GDAXI','^N225','^IXIC','^FTSE','^N100','^IBEX')
first_date <- Sys.Date() - 12500
last_date <- Sys.Date()

# fetch data
df_index <- yf_get(tickers = my_index, 
                     first_date = first_date,
                     last_date = last_date,
                     freq_data = "weekly")

 plot_ly(df_index, type = 'scatter', mode = 'lines') %>%
      add_trace(x = ~ref_date, y = ~price_close, name = ~ticker) %>%
                    layout(title = '<b>Index Price Evolution<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'Price ($)'), legend = list(title=list(text='<b> Index </b>')))



```

```{r best/worst days miss - market timming analysis}
# 
# attach(result_SP)
# detach(result_SP)

result_SP[order(result_SP$ret_closing_prices),]$ret_closing_prices


cumprod(
          result_SP[order(result_SP$ret_closing_prices),]$ret_closing_prices

)

```

```{r commodities - quandl test}
Quandl("LBMA/GOLD")
```

```{r Portfolio read from excel}

# set as direction the one of .Rmd archive; .xlsx and .Rmd mut be on same folder
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
  
my_portfolio <- read_excel("Portfolio.xlsx", sheet="portfolio1")

# clear empty cells in my_data; overwrite it
my_portfolio <- na.omit(my_portfolio)

```

```{r FED interest rates and inflation data -  read from excel}

# set as direction the one of .Rmd archive; .xlsx and .Rmd mut be on same folder
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
  


fed_rates <- read_excel("fed-funds-rate-historical-chart.xlsx", sheet="data")

# clear empty cells in my_data; overwrite it
fed_rates <- na.omit(fed_rates)
colnames(fed_rates) <- c('ref_date','value')
                               
                                  
                                  plot_ly(fed_rates, type = 'scatter', mode = 'lines') %>%
                                           add_trace(x = ~ref_date, y = ~value, name='FED') %>%
                                           layout(title = 'FED Rates')  
            
#https://www.inflation.eu/en/inflation-rates/united-states/historic-inflation/cpi-inflation-united-states.aspx                       
                                                        
us_inflation <- read_excel("US_Inflation_Data.xlsx", sheet="Inflation")

                                        plot_ly(us_inflation, type = 'scatter', mode = 'lines') %>%
                                           add_trace(x = ~Year, y = ~Inflation, name='FED') %>%
                                           layout(title = 'US Inflation')
                                        
                                        
                                        
plot_ly() %>%
    add_trace(data= fed_rates, name="Fed Rates", x = ~ref_date, y = ~value, mode = "lines", type = "scatter") %>%
    add_trace(data= us_inflation, name="Inflation", x = ~Year, y = ~Inflation, mode = "lines+markers", type = "scatter")  %>%   
                          layout(title ="FED vs US Inflation")
                                        
                                        



```


```{r SP500/GOLD/FED - yfR}

# set options for algorithm

#my_ticker <- 'META'
my_ticker <- c('^GSPC')
first_date <- Sys.Date() - 12500
last_date <- Sys.Date()

# fetch data
result_SP <- yf_get(tickers = my_ticker, 
                     first_date = first_date,
                     last_date = last_date,
                     freq_data = "weekly")


my_ticker <- c('GC=F')
# fetch data
result_gold <- yf_get(tickers = my_ticker, 
                     first_date = first_date,
                     last_date = last_date,
                     freq_data = "weekly",
                     thresh_bad_data = 0.55)


df_SPgold <- merge(result_SP, result_gold, by = "ref_date") 
df_SPgold$KPI <- df_SPgold$price_close.x/df_SPgold$price_close.y

  
        ggplotly(
        ggplot(df_SPgold, aes(x=ref_date, y=KPI)) + geom_line()
        )
        
        
 
df_SP_Gold_Fed <- merge(df_SPgold, fed_rates, by = "ref_date")       

 plot_ly(df_SP_Gold_Fed, type = 'scatter', mode = 'lines') %>%
                                           add_trace(x = ~date, y = ~value, name='FED') %>%
                                           layout(title = 'Dividend Evolution')  


```


```{r gathering enterprises tickers with yfR test + Portfolio combined value - yfR}

# set options for algorithm
#my_ticker <- 'META'
my_ticker <- c('FRT','MMM','PG','^GSPC')
my_ticker <- my_portfolio$Ticker
my_ticker <- test_ticker


first_date <- Sys.Date() - 30
last_date <- Sys.Date()


# fetch data of the portfolio
df_historical <- yf_get(tickers = my_ticker,
                        first_date= "1990-01-01",
                        last_date= Sys.Date()-10,
                        thresh_bad_data = 0.2,
                        freq_data="monthly") %>% select(ticker, price_close, ref_date)

        plot_ly(df_historical, type = 'scatter', mode = 'lines')%>%
          add_trace(x = ~ref_date, y = ~price_close, name = ~ticker)

portf_value <- left_join(df_historical, my_portfolio, by=c('ticker'='Ticker')) %>% mutate(value = price_close*as.numeric(Amount) )


portf_value_agg <- aggregate(value ~ ref_date, data = portf_value, FUN = sum)  %>% mutate(Data = "Portfolio" ) 


    
    plot_ly(portf_value_agg, type = 'bar') %>%
      add_trace(x = ~ref_date, y = ~value, name = 'Portfolio')
  

    

sp500 <- setNames(
                yf_get(tickers = "^GSPC",
                        first_date= "1990-01-01",
                        last_date= Sys.Date()-10,
                        freq_data="monthly")   %>% mutate(Data = "Sp500" ) %>% 
          select( ref_date, price_close, Data) ,
          c("ref_date","value","Data")
)


    plot_ly(sp500, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~ref_date, y = ~value, name = ~Data)


sp500$value <- sp500$value*portf_value_agg$value[396]/ sp500$value[395]
#adjust the value to the end of our portfolio value (in the beginning not all stocks are there) 
  
combined <- rbind(sp500, portf_value_agg)


     
     
    plot_ly(combined, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~ref_date, y = ~value, name = ~Data)



```

```{r gathering enterprises tickers - yfR}

#Choose wether to take tickers from the excel or decide in the list below
Manually_define_tickers=1

first_date <- Sys.Date() - 2000
last_date <- Sys.Date() -1

#test_ticker <- 'GC=F'

if(Manually_define_tickers==1){
  
   #my_ticker<- c('PG','JNJ','KO','INTC','GC=F','^GSPC')
   my_ticker<- c('TXN','INTC')
   
}else{
  
    cat("\f")
  
    # gather enterprises' tickers
    tickers<-numeric(dim(my_data)[1])
    
    for (i in 1:dim(my_data)[1]) {
        tickers[i]<- c(my_data[i,2])
    }

}


# get data for all enterprises
result_aux <- yf_get(tickers = my_ticker,                    ### yfR ###
                        first_date=first_date,
                        last_date=last_date,
                        freq_data="weekly")

df_tickers <- result_aux %>% select(ticker, price_close, ref_date)

    
    #ggplot(subset(df_tickers,ticker!="AMZN"), aes(x=ref_date, y=price_close, group=ticker)) + geom_line(aes(colour = ticker))
    
    # ggplotly(
    # ggplot(df_tickers, aes(x=ref_date, y=price_close, group=ticker)) + geom_line(aes(colour = ticker))
    # )

     plot_ly(df_tickers, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~ref_date, y = ~price_close, name = ~ticker)

```


```{r FIAT exchange - priceR test}

exc_rate <- historical_exchange_rates("EUR", to = "USD",
                                    start_date = "2010-01-01",
                                    end_date = "2022-08-30")


colnames(exc_rate)[which(names(exc_rate) == "date")] <- "ref_date"
colnames(exc_rate)[2] <- "ratio"


plot_ly(exc_rate, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~ref_date, y = ~ratio, showlegend = FALSE) %>%
                    layout(title = '<b>USD to EUR<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'Exchange Rate'), legend = list(title=list(text='<b> Date </b>')))


```

```{r evolution with other currency - priceR & yfR}

exc_rate <- historical_exchange_rates("USD", to = "PLN",
                                    start_date = "2000-01-10",
                                    end_date = "2022-11-30")


colnames(exc_rate)[which(names(exc_rate) == "date")] <- "ref_date"
colnames(exc_rate)[2] <- "ratio"


    ggplotly(ggplot(exc_rate, aes(x=ref_date, y=ratio)) + geom_line(aes())
    )


df_tickers_curr <- merge(df_tickers, exc_rate, by = "ref_date")                       # Merge data 1 & 2 and store

df_tickers_curr$price_close_eur = df_tickers_curr$price_close*df_tickers_curr$one_USD_equivalent_to_x_PLN


    ggplotly(ggplot(df_tickers_curr, aes(x=ref_date, y=price_close_eur, group=ticker)) + geom_line(aes(colour = ticker))
    )

```



```{r filter out 2022+ for inflation - yfR for priceR}

#adjust_for_inflation provides the inflation data for a year few months after it ended.

library(dplyr)

df_tickers_inflation <- df_tickers %>% filter(ref_date <= '2023-12-31')

```


```{r inflation data - priceR test }


#   years <- 1920:2000
#   #prices <- 30:100
#   prices <- c(rep(1,length(years)))
#   #adjust_for_inflation(prices, years, "1W", to_date = 2020)
#   inflation_df <- adjust_for_inflation(prices, years, "US", to_date = 2020)
# 
# 

library(priceR)

#show_countries()

Year <- 2000:2023
nominal_prices <- rep(1,length(Year))

df_inflation <- data.frame(Year, nominal_prices)
df_inflation$in_202x_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = 2023) #PriceR


df_inflation <- mutate(df_inflation, inflation_level = ( lag(in_202x_dollars_factor)/in_202x_dollars_factor -1)*100 )


plot_ly(df_inflation, type = 'scatter', mode = 'lines') %>%
      add_trace(x = ~Year, y = ~in_202x_dollars_factor, name="Inflation factor to Y2023") %>%
                    layout(title = '<b>US Historical Inflation<b>', xaxis = list(title = 'Year'), 
                           yaxis = list(title = 'a'),
                           legend = list(title=list(text='<b> Legend </b>')))  %>%
      add_trace(x = ~Year, y = ~inflation_level, name="Inflation Yearly") %>%
                    layout(title = '<b>US Historical Inflation<b>', xaxis = list(title = 'Year'), 
                          yaxis = list(title = '(%)'), 
                          legend = list(title=list(text='<b> Legend </b>')))



plot_ly(df_inflation) %>%
    add_trace(x = ~Year, y = ~in_202x_dollars_factor, type = 'scatter', mode = "lines", yaxis = "y2",name="$ Factor Y2023") %>%
      add_trace(x = ~Year, y = ~inflation_level, type = 'bar',name='Yearly Inflation US')%>%
                    layout(title = '<b>US Inflation Data<b>', xaxis = list(title = 'Date'), 
                           yaxis = list(title = 'Inflation (%Y)'), legend = list(title=list(text='<b> Legend </b>')),
                           yaxis2 = list(overlaying = "y", side = "right",automargin = T,title = "Factor Y2023",range = c(0,3))
                          )


# 
# ggplot(df_inflation,
#            aes(x=year, y=in_202x_dollars_factor)) + geom_line()








```

```{r inflation data - priceR with trycatch - test }



# R program illustrating error handling
# Applying tryCatch

# 
# a=0
# 
# tryCatch(               
#  
#   # Specifying expression
#   expr = {               
#           
#       df_inflation$in_202x_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = 2023) #PriceR
#   
#     print("Everything was fine.")
#   },
#   # Specifying error message
#   error = function(e){         
#     print(paste("There was an error message. Then considering one year less for inflation:","2022"))
#     
#        tryCatch(  
#       
#       expr = {    
#         
#         a=a+1
#                  Year <- 2000:2022
#             nominal_prices <- rep(1,length(Year))
#             df_inflation <- data.frame(Year, nominal_prices)
#               df_inflation$in_202x_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = 2022) #PriceR
#               print("Everything was fine for 2022.")
#             },
#       
#        # Specifying second error message
#           error = function(e){         
#             print(paste("There was an error message for 2022 too. Then considering one year less for inflation:","2023"))
#             
#             a=a+1
#             Year <- 2000:2023
#             nominal_prices <- rep(1,length(Year))
#             df_inflation <- data.frame(Year, nominal_prices)
#             df_inflation$in_202x_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = 2023) #PriceR
#           })
#   },
#   finally = {            
#     print("finally Executed")
#     df_inflation <- mutate(df_inflation, inflation_level = ( lag(in_202x_dollars_factor)/in_202x_dollars_factor -1)*100 )
#   }
# )


```


```{r stock value & inflation correction - yfR & priceR}



df_tickers_inflation["Year"] <- year(df_tickers_inflation$ref_date)

df_tickers_inflation <- merge(df_tickers_inflation, df_inflation, by='Year')

df_tickers_inflation["real_value_202x"] <- df_tickers_inflation$price_close/df_tickers_inflation$in_202x_dollars_factor

#df_tickers_inflation #%>% filter(ticker == 'PG')
    ggplotly(
           ggplot(subset(df_tickers_inflation,ticker!="AMZN"),
           aes(x=ref_date, y=real_value_202x, group=ticker)) + geom_line(aes(colour = ticker))
             )
    

 # ggplotly(
 #             ggplot(subset(df_tickers_inflation,ticker=="PG"),
 #             aes(x=ref_date, y=real_value_202x, group=ticker)) + geom_line(aes(colour = ticker))
 #      )
 
#     
#  ggplotly(
# ggplot(subset(df_tickers_inflation,ticker=="KO"),
#        aes(x=ref_date, y=price_close, group=ticker)) + geom_line(aes(colour = ticker))
# )
 
 
  # 
  #  ggplotly(
  # ggplot(df_tickers_inflation, aes(x=ref_date, y=real_value_202x, group=ticker)) + geom_line(aes(colour = ticker))
  #  )
```


```{r Dividends - quantmod test}

Your_Ticker <- 'KO'

df_divs <- getDividends(Your_Ticker,  #quantmod
             from = "2010-01-01",
             to = Sys.Date()-30, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)



df_divs <- data.frame(date=index(df_divs), coredata(df_divs))
colnames(df_divs) <- c('date','div')



plot_ly(df_divs, type = 'bar')%>%
      add_trace(x = ~date, y = ~div, showlegend = FALSE) %>%
                    layout(title = '<b>Historical Ticker Dividend<b>', xaxis = list(title = 'Date'), 
                 yaxis = list(title = 'USD'), legend = list(title=list(text='<b> Date </b>')))



```



```{r test - quantmod for divs / yfR}

#test_ticker <- 'O'
test_ticker <- 'NKE'
#test_ticker <- 'AMT'


df_divs <- getDividends(test_ticker,  #quantmod
             from = "1970-01-01",
             to = Sys.Date()-30, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


df_historical <- yf_get(tickers = test_ticker, #yfR
                        first_date= "1970-02-01",
                        last_date= Sys.Date()-30,
                        freq_data="daily") %>% select(ticker, price_close, ref_date)



df_divs <- data.frame(date=index(df_divs), coredata(df_divs))
colnames(df_divs) <- c('date','div')



n <- 1
last_exdiv_date = df_divs[n,1]
last_exdiv_amount = df_divs[n,2]

vector <- character(nrow(df_historical))
vector[1] <- last_exdiv_amount


for(i in 1:nrow(df_historical)) {


  #if(pg_historical$ref_date[i] %in% divs$date){
  if( any(divs == as.character(df_historical$ref_date[i])) ){
    n <- n+1
    last_exdiv_date <- divs[n,1]
    last_exdiv_amount <- divs[n,2]
  }else{ #

  #vector[i] <- last_exdiv_amount
  }
  vector[i] <- last_exdiv_amount
}

df_historical$ex_div <- vector
df_historical$ex_div <- as.numeric(df_historical$ex_div)
df_historical$price_close <- as.numeric(df_historical$price_close)

df_historical$yield <- 100*4*df_historical$ex_div/df_historical$price_close


# ggplot(pg_historical, aes(x=ref_date, y=yield)) + geom_line()
# 
# 
# plot_ly(pg_historical, type = 'scatter', mode = 'lines')%>%
#   add_trace(x = ~ref_date, y = ~ex_div, name = 'PG')

    
    
    plot_ly(df_divs, type = 'scatter', mode = 'lines') %>%
      add_trace(x = ~date, y = ~div, name = test_ticker)
    
    plot_ly(df_historical, type = 'scatter', mode = 'lines') %>%
      add_trace(x = ~ref_date, y = ~price_close, name = test_ticker)
    
    plot_ly(df_historical, type = 'scatter', mode = 'lines') %>%
      add_trace(x = ~ref_date, y = ~yield, name = test_ticker) %>%
      add_trace(x = ~ref_date, y = ~ex_div, name = 'ex_div')




### GROUP BY YEAR

divs_agg <- setNames(aggregate(df_divs$div, by=list(Year_div=year(df_divs$date)), FUN=sum),
         c("Year_div","div"))

      plot_ly(divs_agg, type = 'bar')%>%
        add_trace(x = ~Year_div, y = ~div, name = test_ticker)


### 5y div growth


growth_hist=c()
n=5
for(i in 6:nrow(divs_agg)) {

#print(i)
#print(divs_agg$div[i]-divs_agg$div[i-5])
  
  growth_hist[i-n] = ( (divs_agg$div[i]/divs_agg$div[i-n])^(1/n) -1)*100
 
}

growth_df <- data.frame(year_growth=divs_agg$Year_div[- (1:n)], growth_hist)

    plot_ly(growth_df, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~year_growth, y = ~growth_hist, name = test_ticker)



(divs_agg$div[53]-divs_agg$div[52])/divs_agg$div[52]

divs_agg$div[52]*(1+(divs_agg$div[53]-divs_agg$div[52])/divs_agg$div[52])



( (divs_agg$div[53]/divs_agg$div[51])^(1/2)-1 )*100

divs_agg$div[51]*((divs_agg$div[53]/divs_agg$div[51])^(1/2))*((divs_agg$div[53]/divs_agg$div[51])^(1/2))




#5y
( (divs_agg$div[53]/divs_agg$div[53-5])^(1/5) -1)*100
growth_5y = ( (divs_agg$div[53]/divs_agg$div[53-5])^(1/5) )

divs_agg$div[53-5]*(growth_5y^5)


#10y
n<-5
( (divs_agg$div[53]/divs_agg$div[53-n])^(1/n) -1)*100
growth_ny = ( (divs_agg$div[53]/divs_agg$div[53-n])^(1/n) )

divs_agg$div[53-n]*(growth_ny^n)







### SPLITS

df_historical$yieldv2 <- df_historical$yield*c(rep(2,10692),rep(1,13273-10693))


    
    
    plot_ly(df_historical, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~ref_date, y = ~yieldv2, name = test_ticker)%>%
      add_trace(x = ~ref_date, y = ~ex_div, name = 'ex_div')

df_historical$yieldv3 <- df_historical$yieldv2*c(rep(2,6601),rep(1,13273-6602))

    
    plot_ly(df_historical, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~ref_date, y = ~yieldv3, name = test_ticker)%>%
      add_trace(x = ~ref_date, y = ~ex_div, name = 'ex_div')



```



```{r dividend analysys (amount & growth) - yfr & quantmod}



# test_ticker <- c('NKE','PG','O','ABT','CAT','PEP','KO','LEG','VFC','AMT','MO','BLK','CAT','ABBV','T','VZ','SWK','TROW','MRK','PFE','INTC','MMM','MCD','BMY')

#test_ticker <- c('NKE','PG','mc.pa','tyo.4502','t.to')

test_ticker <- c('TROW')





divs <- getDividends(test_ticker[1], 
             from = "1970-01-01",
             to = Sys.Date()-30, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


divs <- data.frame(date=index(divs), coredata(divs))
colnames(divs) <- c('date','div')


divs$ticker <- rep(test_ticker[1],nrow(divs))


for(i in 2:length(test_ticker)) {

  aux <- getDividends(test_ticker[i], 
             from = "1970-01-01",
             to = Sys.Date()-30, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


aux <- data.frame(date=index(aux), coredata(aux))
colnames(aux) <- c('date','div')

aux$ticker <- rep(test_ticker[i],nrow(aux))

#append
divs <- rbind(divs, aux)
 
}


### GROUP BY YEAR & ticker
# 
# aggregate(divs$div, by=list(Year_div=year(divs$date)), FUN=sum)


# #For quarterly growth
divs_agg <- setNames( aggregate(div ~ (date) + ticker, data = divs, FUN = sum, na.rm = TRUE),
                    c("Year_div","ticker","div"))


#For yearly growth
divs_agg <- setNames( aggregate(div ~ year(date) + ticker, data = divs, FUN = sum, na.rm = TRUE),
                    c("Year_div","ticker","div"))



      plot_ly(
        data = divs_agg,
        x = ~Year_div,
        y = ~div,
        type = "bar",
        name = ~ticker,
        color=~ticker
      )  %>%
        layout(title = "<b>Dividend Evolution</b>",
                           xaxis = list(title = 'Year'), 
                            yaxis = list(title = 'USD ($)'), legend = list(title=list(text='<b> Tickers </b>')))
    
    
    






growth_df <- data.frame( #empty dataframe
                            year_growth = integer(),
                             Ticker = character(),
                             Growth_hist = double())



growth_hist=c()
n=1 #years/quarters of growth comparison
c=0

unique(divs_agg$ticker)

for ( j in 1:length(unique(divs_agg$ticker)) ) {
  
  divs_agg_ticker <- filter(divs_agg,ticker %in% unique(divs_agg$ticker)[j])
  
  
  growth_hist=c()
for(i in 6:nrow(divs_agg_ticker)) {


  growth_hist[i-n] = ( (divs_agg_ticker$div[i]/divs_agg_ticker$div[i-n])^(1/n) -1)*100
 
}
  
  
    
  growth_df <-  rbind(growth_df,
                      data.frame(year_growth=divs_agg_ticker$Year_div[- (1:n)], growth_hist) %>% mutate(Ticker = unique(divs_agg$ticker)[j]) 
                      )
  
}

       plot_ly(growth_df, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~year_growth, y = ~growth_hist, name = ~Ticker) %>%
                    layout(title = "<b>Dividend Growth</b>",
                           xaxis = list(title = 'Growth YoY (%)'), 
                            yaxis = list(title = 'Growth (%)'), legend = list(title=list(text='<b> Tickers </b>')))
    
    
#################
# Using the UDF #
#################
    
source("R_Stocks_Analysis_functions.R")  
    
divs_agg <- f_divs_agg( c('TROW'), "2010-01-01",Sys.Date())    
growth_df <- f_growth_df(divs_agg,1)

   
growth_df <- f_growth_df(divs_agg,2)


    
divs_agg <- f_divs_agg( c('TROW','PG'), "2010-01-01",Sys.Date())    
growth_df <- f_growth_df(divs_agg,1)   

growth_df <- f_growth_df(divs_agg,2)   


              
                  plot_ly(
                    data = divs_agg,
                    x = ~Year_div,
                    y = ~div,
                    type = "bar",
                    name = ~ticker,
                    color=~ticker
                  )  %>%
                    layout(title = "<b>Dividend Evolution</b>",
                                       xaxis = list(title = 'Year'), 
                                        yaxis = list(title = 'USD ($)'), legend = list(title=list(text='<b> Tickers </b>')))


            
               plot_ly(growth_df, type = 'scatter', mode = 'lines')%>%
                  add_trace(x = ~year_growth, y = ~growth_hist, name = ~Ticker) %>%
                                layout(title = "<b>Dividend Growth</b>",
                                       xaxis = list(title = 'Growth YoY (%)'), 
                                        yaxis = list(title = 'Growth (%)'), legend = list(title=list(text='<b> Tickers </b>')))
    

```


```{r dividend analysys (amount & growth) - yfr & quantmod - interactive ready}



test_ticker <- c('NKE','PG','JNJ','BMY')

ini_date="2000-01-01"


divs <- getDividends(test_ticker[1], 
             #from = "1970-01-01",
             from = ini_date,
             #to = Sys.Date()-30,
             to = Sys.Date(),
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


divs <- data.frame(date=index(divs), coredata(divs))
colnames(divs) <- c('date','div')




### Divs Evolution ###

divs$ticker <- rep(test_ticker[1],nrow(divs))


for(i in 2:length(test_ticker)) {

  aux <- getDividends(test_ticker[i], 
             #from = "1970-01-01",
             from = ini_date,
             #to = Sys.Date()-30,
             to = Sys.Date(),
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


aux <- data.frame(date=index(aux), coredata(aux))
colnames(aux) <- c('date','div')

aux$ticker <- rep(test_ticker[i],nrow(aux))

#append
divs <- rbind(divs, aux)
 
}



### GROUP BY YEAR & ticker

aggregate(divs$div, by=list(Year_div=year(divs$date)), FUN=sum)


divs_agg <- setNames( aggregate(div ~ year(date) + ticker, data = divs, FUN = sum, na.rm = TRUE),
                    c("Year_div","ticker","div"))

 
      plot_ly(
        data = divs_agg,
        x = ~Year_div,
        y = ~div,
        type = "bar",
        name = ~ticker,
        color=~ticker
      )  %>%
        layout(title = "<b>Dividend Evolution</b>",
                           xaxis = list(title = 'Year'), 
                            yaxis = list(title = 'USD ($)'), legend = list(title=list(text='<b> Tickers </b>')))
      
      
      
     
      plot_ly(
        data = divs_agg,
        x = ~Year_div,
        y = ~div,
        type = "bar",
        name = ~ticker,
        color=~ticker
      ) %>%
          add_trace( data= divs_agg %>% group_by(ticker) %>%  dplyr::mutate(cum_div_ticker = cumsum(div)) %>% mutate(Cum_div_t = paste("Cumulative Div",divs_agg$ticker)) 
                              , name=~Cum_div_t, x = ~Year_div, 
                              y = ~cum_div_ticker,
                              mode = "lines+markers",
                              type = "scatter") %>%
        layout(title = "<b>Dividend Evolution</b>",
                           xaxis = list(title = 'Year'), 
                            yaxis = list(title = 'USD ($)'), legend = list(title=list(text='<b> Tickers </b>')))
      
      

### DIvs growth ###

growth_df <- data.frame( #empty dataframe
                            year_growth = integer(),
                             Ticker = character(),
                             Growth_hist = double()) 



growth_hist=c()
n=1 #dividend growth of year Z vs Z-n (anualized)


unique(divs_agg$ticker)

for ( j in 1:length(unique(divs_agg$ticker)) ) {
  
  divs_agg_ticker <- filter(divs_agg,ticker %in% unique(divs_agg$ticker)[j])
  
  
  growth_hist=c()
for(i in (n+1):nrow(divs_agg_ticker)) {


  growth_hist[i-n] = ( (divs_agg_ticker$div[i]/divs_agg_ticker$div[i-n])^(1/n) -1)*100
 
}
  
  
    
  growth_df <-  rbind(growth_df,
                      data.frame(year_growth=divs_agg_ticker$Year_div[- (1:n)], growth_hist) %>% mutate(Ticker = unique(divs_agg$ticker)[j]) 
                      )
  
}
    
    
    
    plot_ly(growth_df, type = 'scatter', mode = 'lines')%>%
      add_trace(x = ~year_growth, y = ~growth_hist, name = ~Ticker) %>%   
      layout(title =sprintf("Dividend growth %s-y ", n))
    
    
   
```



```{r dividend analysys (amount & growth) - yfr & quantmod - interactive ready}

```


```{r dividend growth vs inflation - quantmod & priceR}


library(tidyr) #for drop_na

Year <- 2000:2023
#nominal_prices <- rnorm(10, mean=10, sd=3)
nominal_prices <- rep(1,length(Year))

df_inflation <- data.frame(Year, nominal_prices)
df_inflation$in_2020_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = 2023) #PriceR



df_inflation <- mutate(df_inflation,
                         yearly_inflation = 100*( lag(in_2020_dollars_factor)/in_2020_dollars_factor -1)
                            )%>% drop_na()


drops <- c("nominal_prices","in_2020_dollars_factor")
# inflation_df[ , !(names(inflation_df) %in% drops)]  %>% 
#   `colnames<-`(c("Year", "div")) %>%
#   mutate(Ticker = 'Infl') 



#compare it with the 1y dividend growth
growth_df <-  rbind(growth_df,
                    df_inflation[ , !(names(df_inflation) %in% drops)]  %>% 
                    `colnames<-`(c("year_growth", "growth_hist")) %>%
                    mutate(Ticker = 'Infl') 
                      )



      
      plot_ly(growth_df, type = 'scatter', mode = 'lines')%>%
        add_trace(x = ~year_growth, y = ~growth_hist, name = ~Ticker) %>%   
      layout(title =sprintf("Dividend growth %s-y vs Inflation", n))


```





```{r historical yield - quantmod & yFr - test}

test_ticker <- 'BMY'

hist_splits <- quantmod::getSplits(test_ticker)


hist_price <- yf_get(tickers = test_ticker,
                        first_date= "1960-01-01",
                        last_date= Sys.Date()-10,
                        thresh_bad_data = 0.2,
                        freq_data="monthly") %>% select(ticker, price_close, ref_date) 
hist_price$ym <- format(as.Date(hist_price$ref_date), "%Y-%m")


hist_divs <- getDividends(test_ticker, 
                   from = "1960-01-01",
                   to = Sys.Date()-10, 
                   src = "yahoo", 
                   auto.assign = TRUE, 
                   auto.update = TRUE, 
                   verbose = FALSE)
      
      
hist_divs <- data.frame(date=index(hist_divs), coredata(hist_divs))
colnames(hist_divs) <- c('ref_date','div')


hist_divs$ym <- format(as.Date(hist_divs$ref_date), "%Y-%m")






#library(tidyr)

df_hist_yield = left_join(hist_price, hist_divs, by=c('ym')) 
df_hist_yield =  fill(df_hist_yield, div, .direction = 'down')
df_hist_yield$div_yield <- 4*100*df_hist_yield$div/df_hist_yield$price_close



plot_ly(df_hist_yield, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~ym, y = ~price_close, name = ~ticker)



plot_ly(df_hist_yield, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~ym, y = ~div, name = ~ticker)



plot_ly(df_hist_yield, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~ym, y = ~div_yield, name = ~ticker)




hist_splits <- data.frame(date=index(hist_splits), coredata(hist_splits))


hist_splits$ref_date = rownames(hist_splits)
colnames(hist_splits) <- c('ref_date','split')
hist_splits$ym <- format(as.Date(hist_splits$ref_date), "%Y-%m")

hist_splits =  hist_splits %>% arrange(desc(ref_date))


hist_splits =  transform(
            hist_splits,
          split_c = cumprod(c(na.omit(split)))
        )


df_hist_yield = left_join(df_hist_yield, hist_splits, by=c('ym')) 

df_hist_yield = fill(df_hist_yield, split_c, .direction = 'up')


df_hist_yield$split_c = df_hist_yield$split_c %>% replace_na(1)



df_hist_yield$yield_corrected <- df_hist_yield$div_yield/df_hist_yield$split_c



plot_ly(df_hist_yield, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~ym, y = ~yield_corrected, name = ~ticker)


plot_ly(df_hist_yield, type = 'scatter', mode = 'lines')%>%
                    add_trace(x = ~ym, y = ~yield_corrected, name = ~ticker)
s
plot_ly(df_hist_yield,y = ~yield_corrected, type = "box",name=~ticker)


```



```{r historical yield - quantmod & yFr - interactive ready}


test_ticker <- c('PG','JNJ','ko','mc.pa')



# historical splits
hist_splits <- quantmod::getSplits(test_ticker[1])
hist_splits <- data.frame(date=index(hist_splits), coredata(hist_splits))
colnames(hist_splits) <- c('ref_date','split')
hist_splits$ticker <- rep(test_ticker[1],nrow(hist_splits))

hist_splits =  hist_splits %>% arrange(desc(ref_date))
      hist_splits =  transform(
            hist_splits,
          split_c = cumprod(c(na.omit(split)))
        )

      for(i in 2:length(test_ticker)) {
      
        aux <- quantmod::getSplits(test_ticker[i])
        aux <- data.frame(date=index(aux), coredata(aux))
        
      colnames(aux) <- c('ref_date','split')
      aux$ticker <- rep(test_ticker[i],nrow(aux))
      
      
      aux =  aux %>% arrange(desc(ref_date))
      aux =  transform(
            aux,
          split_c = cumprod(c(na.omit(split)))
        )
      
      #append
      hist_splits <- rbind(hist_splits, aux)
      }

      
hist_splits$ym <- format(as.Date(hist_splits$ref_date), "%Y-%m")



## historical price

hist_price <- yf_get(tickers = test_ticker,
                        first_date= "1960-01-01",
                        last_date= Sys.Date()-10,
                        thresh_bad_data = 0.2,
                        freq_data="monthly") %>% select(ticker, price_close, ref_date) 
hist_price$ym <- format(as.Date(hist_price$ref_date), "%Y-%m")


## historical divs
divs <- getDividends(test_ticker[1], 
             from = "1960-01-01",
             to = Sys.Date()-10, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


divs <- data.frame(date=index(divs), coredata(divs))
colnames(divs) <- c('ref_date','div')




### Divs Evolution ###

divs$ticker <- rep(test_ticker[1],nrow(divs))


for(i in 2:length(test_ticker)) {

  aux <- getDividends(test_ticker[i], 
             from = "1960-01-01",
             to = Sys.Date()-10, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


aux <- data.frame(date=index(aux), coredata(aux))
colnames(aux) <- c('ref_date','div')

aux$ticker <- rep(test_ticker[i],nrow(aux))

#append
divs <- rbind(divs, aux)
 
}
       
       
divs$ym <- format(as.Date(divs$ref_date), "%Y-%m")




#join the DF's
df_hist_yield = left_join(hist_price, divs, by=c('ym','ticker')) 
df_hist_yield = left_join(df_hist_yield, hist_splits, by=c('ym','ticker')) 


for(i in 1:length(test_ticker)) {

  df_hist_yield[df_hist_yield$ticker== test_ticker[i],] =  fill(df_hist_yield[df_hist_yield$ticker== test_ticker[i],] , div, .direction = 'down')
  
  df_hist_yield[df_hist_yield$ticker== test_ticker[i],] =  fill(df_hist_yield[df_hist_yield$ticker== test_ticker[i],] , split_c, .direction = 'up')

}


df_hist_yield$div_yield <- 4*100*df_hist_yield$div/df_hist_yield$price_close
df_hist_yield$split_c = df_hist_yield$split_c %>% replace_na(1)
df_hist_yield$yield_corrected <- df_hist_yield$div_yield/df_hist_yield$split_c
      
      plot_ly(df_hist_yield, type = 'scatter', mode = 'lines')%>%
                          add_trace(x = ~ym, y = ~price_close, name = ~ticker)
      
      
      plot_ly(df_hist_yield, type = 'scatter', mode = 'lines')%>%
                          add_trace(x = ~ym, y = ~div, name = ~ticker)
      
      
      plot_ly(df_hist_yield, type = 'scatter', mode = 'lines')%>%
                          add_trace(x = ~ym, y = ~yield_corrected, name = ~ticker)
      
      
      plot_ly(df_hist_yield,y = ~yield_corrected, type = "box",name=~ticker)
      
```



```{r YoC - quantmod & yFr & priceR - 1 ticker}



test_ticker <- c('PEP')

invest = 1000

initial_date="1995-01-01"
ending_date="2022-01-01"



#inflation & money input (priceR)
Year <- (year(initial_date)-1):(year(ending_date)-1) #2000 to 2023
#nominal_prices <- rnorm(10, mean=10, sd=3)
nominal_prices <- rep(1,length(Year))

df_inflation <- data.frame(Year, nominal_prices)
df_inflation$in_2020_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = (year(ending_date)-1)) ###PriceR###



df_inflation <- mutate(df_inflation,
                         yearly_inflation = 100*( lag(in_2020_dollars_factor)/in_2020_dollars_factor -1)
                            )%>% drop_na()


df_inflation$money_input_infl <- invest/df_inflation$in_2020_dollars_factor #monthly input corrected by inflation





## historical price (yfR)

hist_price <- yf_get(tickers = test_ticker,
                        first_date= initial_date,
                        last_date= ending_date,
                        thresh_bad_data = 0.2,
                        freq_data="monthly") %>% select(ticker, price_close, ref_date) 
hist_price$ym <- format(as.Date(hist_price$ref_date), "%Y-%m")
hist_price$Year <- as.integer(format(as.Date(hist_price$ref_date), "%Y"))


       plot_ly(hist_price, type = 'scatter', mode = 'lines')%>%
                          add_trace(x = ~ym, y = ~price_close, name = ~ticker)
      
hist_price_infl <- left_join(hist_price, df_inflation, by=c('Year')) 
hist_price_infl$Stocks <- hist_price_infl$money_input_infl/hist_price_infl$price_close


       plot_ly(hist_price_infl, type = 'bar') %>%
                          add_trace(x = ~ym, y = ~Stocks, name = ~ticker)  %>%   
                          layout(title ="Number of stocks that were bought")

       sum(hist_price_infl$money_input_infl)/sum(hist_price_infl$Stocks) #DCA for 1 ticker

## historical divs (yfR)
divs <- getDividends(test_ticker[1], 
             from = initial_date,
             to = ending_date, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


divs <- data.frame(date=index(divs), coredata(divs))
colnames(divs) <- c('ref_date','div')



tail(divs, n =1)$div*4 #current anualized dividend
tail(divs, n =1)$div*4*sum(hist_price_infl$Stocks) #annual cash flow today
tail(divs, n =1)$div*4*sum(hist_price_infl$Stocks)/sum(hist_price_infl$money_input_infl)+1 #return div today = YoC


(tail(hist_price, n =1)$price_close*sum(hist_price_infl$Stocks)/sum(hist_price_infl$money_input_infl)+1) #capital ret
(tail(hist_price, n =1)$price_close*sum(hist_price_infl$Stocks)/sum(hist_price_infl$money_input_infl)+1)^(1/(year(ending_date)-year(initial_date))) #capital ret anualized


df_95_201x = head(hist_price_infl, n =12*(year(ending_date)-year(initial_date)-7))

                                                                                  #return div on year x = YoC on year x
tail(divs, n =1)$div*4*sum(df_95_201x$Stocks)/sum(df_95_201x$money_input_infl)+1 #return div today = YoC today
(tail(df_95_201x, n =1)$price_close*sum(df_95_201x$Stocks)/sum(df_95_201x$money_input_infl)+1)^(1/(year(ending_date)-year(initial_date)))#capital ret anualized on year x
(tail(hist_price, n =1)$price_close*sum(df_95_201x$Stocks)/sum(df_95_201x$money_input_infl)+1)^(1/(year(ending_date)-year(initial_date)))#capital ret anualized today



#if buying at the higher price vs the money input corrected by inflation:
df_95_201x$Stocks <- min(df_95_201x$Stocks)
tail(divs, n =1)$div*4*sum(df_95_201x$Stocks)/sum(df_95_201x$money_input_infl)+1 #return div today = YoC today
(tail(hist_price, n =1)$price_close*sum(df_95_201x$Stocks)/sum(df_95_201x$money_input_infl)+1)^(1/(year(ending_date)-year(initial_date)))#capital ret anualized today

```


```{r YoC - quantmod & yFr & priceR - multi ticker}



#test_ticker <- c('JNJ','BHP')
test_ticker <- c('JNJ','ABT','PG','VFC','O','ABT','PEP','KO','LEG','T','VZ','SWK','TROW','MRK','PFE','INTC','MMM','MCD','BMY','RIO','BHP','O','NKE','CAT','WBA')

invest = 1000/length(unique(test_ticker)) #it will assume that all given tickers are included in the hist_price data frame from the given initial_date (!!!)

#portf_split=length(unique(test_ticker))



initial_date="1998-01-01"
ending_date="2022-01-01"



#inflation & money input (priceR)
Year <- (year(initial_date)-1):(year(ending_date)-1) #2000 to 2023
#nominal_prices <- rnorm(10, mean=10, sd=3)
nominal_prices <- rep(1,length(Year))

df_inflation <- data.frame(Year, nominal_prices)
df_inflation$in_2020_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = (year(ending_date)-1)) ###PriceR###



df_inflation <- mutate(df_inflation,
                         yearly_inflation = 100*( lag(in_2020_dollars_factor)/in_2020_dollars_factor -1)
                            )%>% drop_na()


df_inflation$money_input_infl <- invest/df_inflation$in_2020_dollars_factor #monthly input corrected by inflation





## historical price (yfR)

hist_price <- yf_get(tickers = test_ticker,
                        first_date= initial_date,
                        last_date= ending_date,
                        thresh_bad_data = 0.2,
                        freq_data="monthly") %>% select(ticker, price_close, ref_date) 
hist_price$ym <- format(as.Date(hist_price$ref_date), "%Y-%m")
hist_price$Year <- as.integer(format(as.Date(hist_price$ref_date), "%Y"))


       plot_ly(hist_price, type = 'scatter', mode = 'lines')%>%
                          add_trace(x = ~ym, y = ~price_close, name = ~ticker)
      
hist_price_infl <- left_join(hist_price, df_inflation, by=c('Year')) 
hist_price_infl$Stocks <- hist_price_infl$money_input_infl/hist_price_infl$price_close          #no round down
#                                                                                               #round down


       plot_ly(hist_price_infl, type = 'bar')%>%
                          add_trace(x = ~ym, y = ~Stocks, name = ~ticker)  %>%   
                          layout(title ="Number of stocks that were bought")

       #sum(hist_price_infl$money_input_infl)/sum(hist_price_infl$Stocks) #DCA for one ticker
       
       DCA_df <- setNames(
          aggregate(hist_price_infl$Stocks, by=list(Category=hist_price_infl$ticker), FUN=sum),  # setNames function
                       c("ticker", "Stocks"))
       DCA_df$DCA <- sum(hist_price_infl$money_input_infl)/length(unique(test_ticker))/DCA_df$Stocks
     
       
## historical divs (yfR)


divs <- getDividends(test_ticker[1], 
             from = initial_date,
             to = ending_date, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


divs <- data.frame(date=index(divs), coredata(divs))
colnames(divs) <- c('date','div')




### Divs Evolution ###

divs$ticker <- rep(test_ticker[1],nrow(divs))


for(i in 2:length(test_ticker)) {

  aux <- getDividends(test_ticker[i], 
             from = initial_date,
             to = ending_date, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


aux <- data.frame(date=index(aux), coredata(aux))
colnames(aux) <- c('date','div')

aux$ticker <- rep(test_ticker[i],nrow(aux))

#append
divs <- rbind(divs, aux)
 
}



### GROUP BY YEAR & ticker

aggregate(divs$div, by=list(Year_div=year(divs$date)), FUN=sum)


divs_agg <- setNames( aggregate(div ~ year(date) + ticker, data = divs, FUN = sum, na.rm = TRUE),
                    c("Year_div","ticker","div"))
    
    
      #(!!!)
      length(unique( divs_agg[divs_agg$Year_div== 1998,]$ticker)) < length(unique(test_ticker)) #if true some stocks are missing in the first year selected
      divs_agg[divs_agg$Year_div== 1998,] %>%
             filter(!ticker %in% test_ticker)
      
      
      unique( divs_agg[divs_agg$Year_div== 1998,]$ticker)[!(unique( divs_agg[divs_agg$Year_div== 1998,]$ticker) %in% test_ticker)]
      


### Today's Analysis ###

#aggregate(divs_agg$div, by = list(divs_agg$ticker), max) #take the biggest dividend, can provide miss-leading results for non DGI
#divs_agg %>% group_by(ticker) %>% top_n(1, Year_div) #take the last dividend -> #current dividend
#hist_price %>% group_by(ticker) %>% top_n(1, ym) #take the last stock value in the market -> #current annualized dividend

      #divs_agg %>% group_by(ticker) %>% top_n(1, Year_div)
      #divs_agg %>% group_by(ticker) %>% top_n(2, Year_div)
      #divs_agg[divs_agg$Year_div== 2023,]%>% group_by(ticker)

DCA_df_divs <- left_join(DCA_df, divs_agg[divs_agg$Year_div== 2023,]%>% group_by(ticker), by=c('ticker'='ticker'))       
#DCA_df_divs <- left_join(DCA_df, divs_agg %>% group_by(ticker) %>% top_n(1, Year_div), by=c('ticker'='ticker')) 
DCA_df_divs <- left_join(DCA_df_divs, hist_price %>% group_by(ticker) %>% top_n(1, ym), by=c('ticker'='ticker')) 

DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
sum(DCA_df_divs$div_cash_flow) #total cash flow today thanks to dividends


sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl$money_input_infl)+1 #return div today = YoC

DCA_df_divs$capital_value <- DCA_df_divs$Stocks*DCA_df_divs$price_close #capital value
DCA_df_divs$invested <- DCA_df_divs$Stocks*DCA_df_divs$DCA #capital invested
DCA_df_divs$an_growth <- (DCA_df_divs$capital_value/DCA_df_divs$invested+1)^(1/(year(ending_date)-year(initial_date)))#capital ret anualized today per ticker

(sum(DCA_df_divs$capital_value)/sum(DCA_df_divs$invested)+1)^(1/(year(ending_date)-year(initial_date)))#portfolio capital return anualized (today)



### Stopping the investment Z years ago ###


Z=12


#df_95_201x = head(hist_price_infl, n = 12*(year(ending_date)-year(initial_date)-Z)) #for 1 ticker


df_95_201x =  data.table(hist_price_infl, key="ticker")
df_95_201x = df_95_201x[, head(.SD, 12*(year(ending_date)-year(initial_date)-Z) ), by=ticker]



       DCA_df <- setNames(
          aggregate(df_95_201x$Stocks, by=list(Category=df_95_201x$ticker), FUN=sum),  # setNames function
                       c("ticker", "Stocks"))
       DCA_df$DCA <- sum(df_95_201x$money_input_infl)/DCA_df$Stocks




DCA_df_divs <- left_join(DCA_df, divs_agg %>% group_by(ticker) %>% top_n(1, Year_div), by=c('ticker'='ticker')) 
DCA_df_divs <- left_join(DCA_df_divs, hist_price %>% group_by(ticker) %>% top_n(1, ym), by=c('ticker'='ticker')) 

DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
sum(DCA_df_divs$div_cash_flow) #total cash flow today thanks to dividends       
sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl$money_input_infl)+1 #return div today = YoC       
       
       
                                                                                  
#tail(divs, n =1)$div*4*sum(df_95_201x$Stocks)/sum(df_95_201x$money_input_infl)+1 #return div today = YoC today



### Stopping the investment Z years ago % Starting after Y years ###


Z=12 #if 98 to 2022 ---> investing from 2000 to 2010
Y=2




df_95_201x =  data.table(hist_price_infl, key="ticker")
df_95_201x = df_95_201x[, head(.SD, 12*(year(ending_date)-year(initial_date)-Z) ), by=ticker]
df_9x_201x = df_95_201x[df_95_201x$Year>= 1998+Y,]


       DCA_df <- setNames(
          aggregate(df_9x_201x$Stocks, by=list(Category=df_9x_201x$ticker), FUN=sum),  # setNames function
                       c("ticker", "Stocks"))
       DCA_df$DCA <- sum(df_9x_201x$money_input_infl)/DCA_df$Stocks




DCA_df_divs <- left_join(DCA_df, divs_agg %>% group_by(ticker) %>% top_n(1, Year_div), by=c('ticker'='ticker')) 
DCA_df_divs <- left_join(DCA_df_divs, hist_price %>% group_by(ticker) %>% top_n(1, ym), by=c('ticker'='ticker')) 

DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
sum(DCA_df_divs$div_cash_flow) #total cash flow today thanks to dividends       
sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl$money_input_infl)+1 #return div today = YoC      

DCA_df_divs$capital_value <- DCA_df_divs$Stocks*DCA_df_divs$price_close #capital value
DCA_df_divs$invested <- DCA_df_divs$Stocks*DCA_df_divs$DCA #capital invested
DCA_df_divs$an_growth <- (DCA_df_divs$capital_value/DCA_df_divs$invested+1)^(1/(year(ending_date)-(1998+Y)))*100-100#capital ret anualized today per ticker
       
      
      plot_ly(DCA_df_divs, labels = ~ticker, values = ~div_cash_flow, type = 'pie')%>%   
                          layout(title ="Split of dividend CF Today")
      plot_ly(DCA_df_divs, labels = ~ticker, values = ~invested, type = 'pie') %>%   
                          layout(title ="Split of investment")
      plot_ly(DCA_df_divs, labels = ~ticker, values = ~capital_value, type = 'pie') %>%   
                          layout(title ="Split of capital value Today")
      plot_ly(DCA_df_divs, type = 'bar') %>%
      add_trace(x = ~ticker, y = ~an_growth, name = 'Anual Growth per Ticker')
      
      
      
      
      
### Trend of YoC over the years, when investing from Y to Z ###      
      
      
      
      
historical_yield <- list()

      
      
 for ( j in 2010:2020 ) {
  #divs_agg %>% group_by(ticker) %>% filter( Year_div == j)  
   #divs_agg %>% group_by(ticker) %>% top_n(1, Year_div)
   
   

DCA_df_divs <- left_join(DCA_df, divs_agg %>% group_by(ticker) %>% filter( Year_div == j)  , by=c('ticker'='ticker')) 
DCA_df_divs <- left_join(DCA_df_divs, hist_price %>% group_by(ticker) %>% top_n(1, ym), by=c('ticker'='ticker')) 

DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
sum(DCA_df_divs$div_cash_flow) #total cash flow today thanks to dividends

(sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl$money_input_infl)+1)*100-100 #return div today = YoC   
   
historical_yield <- append(historical_yield, 
(sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl$money_input_infl)+1)*100-100)
   
 }
      
      historical_yield =unlist(historical_yield)
  yearz =  2010:2020
  
  dfz = data.frame(historical_yield,yearz)
  
 
      
    
    plot_ly( dfz, type = 'bar') %>%
      add_trace(x = ~yearz, y = ~historical_yield, name = 'Portfolio')%>%   
                          layout(title ="Historical YoC of the Portfolio")
      
      
      
      
      

```




```{r YoC - quantmod & yFr & priceR - multi ticker - interactive ready}


#test_ticker <- c('JNJ','BHP')
test_ticker <- c('JNJ','PG','PFE','KO')
#test_ticker <- c('PG')


#length(unique(test_ticker))

invest = 1000 #it will assume that all given tickers are included in the hist_price data frame from the given initial_date (!!!)


initial_date="2000-01-01" #year(initial_date)
ending_date="2022-01-01"

  initial_investment_date <- "2000-01-01"
  final_investment_date <- "2010-01-01"



#inflation & money input (priceR)
Year <- (year(initial_date)-1):(year(ending_date)-1) #2000 to 2023
#nominal_prices <- rnorm(10, mean=10, sd=3)
nominal_prices <- rep(1,length(Year))

df_inflation <- data.frame(Year, nominal_prices)
df_inflation$in_2020_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = (year(ending_date)-1)) ###PriceR###


df_inflation <- mutate(df_inflation,
                         yearly_inflation = 100*( lag(in_2020_dollars_factor)/in_2020_dollars_factor -1)
                            )%>% drop_na()


#To check another sources of inflation:
#df_inflation_2 <- read_excel("US_Inflation_Data.xlsx", sheet="Inflation")
#df_inflation_2 <- df_inflation_2[order(df_inflation_2$Year),]

df_inflation$money_input_infl <-invest/length(unique(test_ticker))/df_inflation$in_2020_dollars_factor #monthly input corrected by inflation and already divided by ticker number (!!!) so it assumes that all tickers are available every year considered 
#Yearly money input inflation corrected per ticker


df_inflation$money_input_infl_year <- invest/df_inflation$in_2020_dollars_factor 



## historical price (yfR)

df_historical <- yf_get(tickers = test_ticker,     ### yfR ###
                        first_date= initial_date,
                        last_date= ending_date,
                        thresh_bad_data = 0.2,
                        freq_data="monthly") %>% select(ticker, price_close, ref_date) 
df_historical$ym <- format(as.Date(df_historical$ref_date), "%Y-%m")
df_historical$Year <- as.integer(format(as.Date(df_historical$ref_date), "%Y"))


       plot_ly(df_historical, type = 'scatter', mode = 'lines')%>%
                          add_trace(x = ~ym, y = ~price_close, name = ~ticker)%>%   
                          layout(title ="Ticker Value Evolution")
      
hist_price_infl <- left_join(df_historical, df_inflation, by=c('Year')) 
hist_price_infl$Stocks <- hist_price_infl$money_input_infl/hist_price_infl$price_close          #no round down !!!!!!!!
#                                                                                               #round down


       plot_ly(hist_price_infl, type = 'bar')%>%
                          add_trace(x = ~ym, y = ~Stocks, name = ~ticker)  %>%   
                          layout(title ="Number of stocks that were bought")

       #sum(hist_price_infl$money_input_infl)/sum(hist_price_infl$Stocks) #DCA for one ticker
       
                                                                            
       
       #For multi ticker & filtering per the future sliders
       
       hist_price_infl_filtered = hist_price_infl[hist_price_infl$Year>= year(initial_investment_date) &
                       hist_price_infl$Year<= year(final_investment_date)  ,]
       
       
       DCA_df <- setNames(
          aggregate(hist_price_infl_filtered$Stocks,                  #created with the already filtered hist price & money_input
                        by=list(Category=hist_price_infl_filtered$ticker),
                        FUN=sum),  # setNames function
                       c("ticker", "Stocks"))
       
       DCA_df$DCA <- (sum(hist_price_infl_filtered$money_input_infl)/length(unique(test_ticker)))/DCA_df$Stocks
                                        #all the money invested per ticker               #ticker amount
     
       
### historical divs (yfR)


divs <- getDividends(test_ticker[1],  ### QuandMod ###
             from = initial_date,
             to = ending_date, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


divs <- data.frame(date=index(divs), coredata(divs))
colnames(divs) <- c('date','div')




### Divs Evolution ###

divs$ticker <- rep(test_ticker[1],nrow(divs))


for(i in 2:length(test_ticker)) {

  aux <- getDividends(test_ticker[i],  ### QuandMod ###
             from = initial_date,
             to = ending_date, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


aux <- data.frame(date=index(aux), coredata(aux))
colnames(aux) <- c('date','div')

aux$ticker <- rep(test_ticker[i],nrow(aux))

#append
divs <- rbind(divs, aux)
 
}



### GROUP BY YEAR & ticker

divs_agg <- setNames( aggregate(div ~ year(date) + ticker, data = divs, FUN = sum, na.rm = TRUE),
                    c("Year_div","ticker","div")) ##aggregated per Year & Ticker
    
    
      #(!!!)
      length(unique( divs_agg[divs_agg$Year_div== year(initial_date),]$ticker)) < length(unique(test_ticker)) #if true some stocks are missing in the first year selected
      length(unique( divs_agg[divs_agg$Year_div== year(initial_investment_date),]$ticker)) < length(unique(test_ticker))
      
      

### Delayed Start&Stop of buying the tickers ###



DCA_df_divs <- left_join(DCA_df, divs_agg %>% group_by(ticker) %>% top_n(1, Year_div), by=c('ticker'='ticker')) #join to latest values
#DCA_df_divs <- left_join(DCA_df_divs, hist_price_infl_filtered %>% group_by(ticker) %>% top_n(1, ym), by=c('ticker'='ticker'))#join to latest values 


DCA_df_divs$invested <- DCA_df_divs$Stocks*DCA_df_divs$DCA
DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
DCA_df_divs$YoC_Ticker <- ((DCA_df_divs$div_cash_flow)/(DCA_df_divs$invested)+1)*100-100 



    
    plot_ly( DCA_df_divs, type = 'bar') %>%
      add_trace(x = ~ticker, y = ~YoC_Ticker, name = 'Portfolio YoC') %>%   
                          layout(title = paste("YoC TODAY* per ticker with last buy on ",final_investment_date))
                                        


sum(DCA_df_divs$div_cash_flow) #total cash flow today thanks to dividends       
(sum(DCA_df_divs$div_cash_flow)/sum(DCA_df_divs$invested)+1)*100-100  #return div TODAY (latest available dividend date) = YoC      


#DCA_df_divs$capital_value <- DCA_df_divs$Stocks*DCA_df_divs$price_close #capital value
#DCA_df_divs$invested <- DCA_df_divs$Stocks*DCA_df_divs$DCA #capital invested
#DCA_df_divs$an_growth <- (DCA_df_divs$capital_value/DCA_df_divs$invested+1)^(1/(year(ending_date)-(year(initial_date)+Y)))*100-100#capital ret anualized today per ticker





      
historical_yield <- list()

historical_CF <- list()

# j=2023
# DCA_df_divs <- left_join(DCA_df, divs_agg %>% group_by(ticker) %>% filter( Year_div == j)  , by=c('ticker'='ticker'))
# DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
# (sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl_filtered[hist_price_infl_filtered$Year <= j ,]$money_input_infl)+1)*100-100


 for ( j in 2000:2023 ) {
  #divs_agg %>% group_by(ticker) %>% filter( Year_div == j)  
   #divs_agg %>% group_by(ticker) %>% top_n(1, Year_div)
   
       
                                       
    DCA_df_divs <- left_join(DCA_df, divs_agg %>% group_by(ticker) %>% filter( Year_div == j)  , by=c('ticker'='ticker')) 
    #DCA_df_divs <- left_join(DCA_df_divs, hist_price %>% group_by(ticker) %>% top_n(1, ym), by=c('ticker'='ticker')) 
    
    DCA_df_divs$div_cash_flow <- DCA_df_divs$Stocks*DCA_df_divs$div
    #print(sum(DCA_df_divs$div_cash_flow)) #total cash flow today thanks to dividends
    
    #(sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl$money_input_infl)+1)*100-100 #return div today = YoC   
       
    historical_yield <- append(
          historical_yield, 
          (sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl_filtered[hist_price_infl_filtered$Year <= j ,]$money_input_infl)+1)*100-100
    )
    
       historical_CF <- append(
          historical_CF, 
          sum(DCA_df_divs$div_cash_flow)
        )
       
       
    #rint(j)
    #divide the cash flow of the year looped vs all the moneyinputed until that year looped
    #print((sum(DCA_df_divs$div_cash_flow)/sum(hist_price_infl_filtered[hist_price_infl_filtered$Year <= j #,]$money_input_infl)+1)*100-100)
 }
      
  historical_yield =unlist(historical_yield)
  historical_CF =unlist(historical_CF)
  yearz =  2000:2023
  
  dfz = data.frame(historical_yield,historical_CF,yearz)
  
  
  
     plot_ly( dfz, type = 'bar') %>%
      add_trace(x = ~yearz, y = ~historical_yield, name = 'Portfolio YoC') %>%   
                          layout(title ="Historical YoC of the Portfolio")
     
  
     plot_ly( dfz, type = 'bar') %>%
      add_trace(x = ~yearz, y = ~historical_CF, name = 'Portfolio CF') %>%   
                          layout(title ="Historical CF of the Portfolio")
    
    plot_ly() %>% 
          add_trace(data= dfz, x = ~yearz, y = ~historical_CF, name = "Portfolio CF", type = "bar") %>%
          add_trace(data= aggregate(money_input_infl ~ Year, data = hist_price_infl_filtered, FUN = sum), name="Monetary Input", x = ~Year, y = ~money_input_infl, mode = "lines+markers", type = "scatter") %>%   
                          layout(title ="Historical CF vs Monetary Input")
     
     

ay <- list(
  tickfont = list(color = "red"),
  overlaying = "y",
  side = "right",
  title = "<b>$</b> invested")

plot_ly() %>% 
          add_trace(data= dfz, x = ~yearz, y = ~historical_yield, name = "historical yield", type = "bar") %>%
          add_trace(data= aggregate(money_input_infl ~ Year, data = hist_price_infl_filtered, FUN = sum), name="Monetary_input", x = ~Year, y = ~money_input_infl, yaxis = "y2", mode = "lines+markers", type = "scatter")  %>%
          layout(
                title = "Historical YoC of the Portfolio vs Monetary input", yaxis2 = ay,
                xaxis = list(title="Year"),
                yaxis = list(title="<b>%</b> YoC")
          )%>%
         layout(plot_bgcolor='#e5ecf6',
              xaxis = list(
                zerolinecolor = '#ffff',
                zerolinewidth = 2,
                gridcolor = 'ffff'),
              yaxis = list(
                zerolinecolor = '#ffff',
                zerolinewidth = 2,
                gridcolor = 'ffff')
          ) 




   
```



```{r YoC - quantmod & yFr & priceR - multi ticker - RE-INVESTING - interactive ready}



taxed <- 0.85
test_ticker <- c('JNJ','PG','PFE','T')

invest = 1000 #it will assume that all given tickers are included in the hist_price data frame from the given initial_date (!!!)


initial_date="2005-01-01" #year(initial_date)
ending_date="2023-12-31"

  initial_investment_date <- "2005-01-01"
  final_investment_date <- "2008-12-31"



#inflation & money input (priceR)
Year <- (year(initial_date)-1):(year(ending_date)) #2018 to 2023

#nominal_prices <- rnorm(10, mean=10, sd=3)
nominal_prices <- rep(1,length(Year))

df_inflation <- data.frame(Year, nominal_prices)
df_inflation$in_2020_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = (year(ending_date))) ###PriceR###


#if API error: assume no inflation to continue 
#df_inflation$in_2020_dollars_factor <-  rep(1,length(Year))


df_inflation <- mutate(df_inflation,
                         yearly_inflation = 100*( lag(in_2020_dollars_factor)/in_2020_dollars_factor -1)
                            )%>% drop_na()




df_inflation$money_input_infl <-invest/length(unique(test_ticker))/df_inflation$in_2020_dollars_factor #monthly input corrected by inflation and already divided by ticker number (!!!) so it assumes that all tickers are available every year considered 
#Yearly money input inflation corrected per ticker



df_inflation$money_input_infl_year <- invest/df_inflation$in_2020_dollars_factor 



#Not all the years the investment were happening ->

df_inflation[df_inflation$Year<year(initial_investment_date)  ,]$money_input_infl = 0
df_inflation[df_inflation$Year<year(initial_investment_date)  ,]$money_input_infl_year = 0


df_inflation[df_inflation$Year>year(final_investment_date)  ,]$money_input_infl = 0
df_inflation[df_inflation$Year>year(final_investment_date)  ,]$money_input_infl_year = 0




## historical price (yfR)

df_historical <- yf_get(tickers = test_ticker,     ### yfR ###
                        first_date= initial_date,
                        last_date= ending_date,
                        thresh_bad_data = 0.2,
                        freq_data="monthly") %>% select(ticker, price_close, ref_date) 
df_historical$ym <- format(as.Date(df_historical$ref_date), "%Y-%m")
df_historical$Year <- as.integer(format(as.Date(df_historical$ref_date), "%Y"))


       plot_ly(df_historical, type = 'scatter', mode = 'lines')%>%
                          add_trace(x = ~ym, y = ~price_close, name = ~ticker)%>%   
                          layout(title ="Ticker Value Evolution")
      
hist_price_infl <- left_join(df_historical, df_inflation, by=c('Year')) 
hist_price_infl$Stocks <- hist_price_infl$money_input_infl/hist_price_infl$price_close          #no round down !!!!!!!!
#                                                                                               #round down


       plot_ly(hist_price_infl, type = 'bar')%>%
                          add_trace(x = ~ym, y = ~Stocks, name = ~ticker)  %>%   
                          layout(title ="Number of stocks that were bought")
       
       
       plot_ly(hist_price_infl, type = 'bar')%>%
                          add_trace(x = ~Year, y = ~Stocks, name = ~ticker)  %>%   
                          layout(title ="Number of stocks that were bought  - NO RE-INVESTMENT")
       
       
       
       
       
   hist_price_infl_group = hist_price_infl %>% group_by(ticker ) %>% dplyr::mutate(cum_stocks_ticker = cumsum(replace_na(Stocks, 0))) %>% select(ticker , ym , Year, cum_stocks_ticker)
   
   

# 
#               plot_ly(  hist_price_infl %>% group_by(ticker ) %>% dplyr::mutate(cum_stocks_ticker = cumsum(Stocks)) %>% select(ticker , ym , cum_stocks_ticker),
#                        type = 'bar') %>%
#                           add_trace(x = ~ym,
#                                     y = ~cum_stocks_ticker,
#                                     name = ~ticker)  %>%
#                           layout(title ="Number of stocks that were bought (Cumulative per Ticker)")

              
   
              plot_ly(  hist_price_infl_group,
                       type = 'bar') %>%
                          add_trace(x = ~ym,
                                    y = ~cum_stocks_ticker,
                                    name = ~ticker)  %>%   
                          layout(title ="Number of stocks that were bought (Cumulative per Ticker) - NO RE-INVESTMENT")
              
                 
                 
              #           
              # plot_ly(  hist_price_infl_group %>% group_by(ticker, Year) %>% filter(cum_stocks_ticker == max(cum_stocks_ticker)),
              #          type = 'bar') %>%
              #             add_trace(x = ~Year,
              #                       y = ~cum_stocks_ticker,
              #                       name = ~ticker)  %>%   
              #             layout(title ="Number of stocks that were bought (Cumulative per Ticker) - NO RE-INVESTMENT")
              # 
              # 
 
       
### historical divs (yfR)


divs <- getDividends(test_ticker[1],  ### QuandMod ###
             from = initial_date,
             to = ending_date, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


divs <- data.frame(date=index(divs), coredata(divs))
colnames(divs) <- c('date','div')




### Divs Evolution ###

divs$ticker <- rep(test_ticker[1],nrow(divs))


for(i in 2:length(test_ticker)) {

  aux <- getDividends(test_ticker[i],  ### QuandMod ###
             from = initial_date,
             to = ending_date, 
             src = "yahoo", 
             auto.assign = TRUE, 
             auto.update = TRUE, 
             verbose = FALSE)


aux <- data.frame(date=index(aux), coredata(aux))
colnames(aux) <- c('date','div')

aux$ticker <- rep(test_ticker[i],nrow(aux))

#append
divs <- rbind(divs, aux)
 
}



### GROUP BY YEAR & ticker

divs_agg <- setNames( aggregate(div ~ year(date) + ticker, data = divs, FUN = sum, na.rm = TRUE),
                    c("Year_div","ticker","div")) ##aggregated per Year & Ticker
    


                
              plot_ly(divs_agg,
                      type = 'bar') %>%
                          add_trace(x = ~Year_div,
                                    y = ~div,
                                    name = ~ticker)  %>%   
                          layout(title ="Historical Div (per ticker)")

   
    
      #(!!!)
      length(unique( divs_agg[divs_agg$Year_div== year(initial_date),]$ticker)) < length(unique(test_ticker)) 
      #if true some stocks are missing in the first year selected
      length(unique( divs_agg[divs_agg$Year_div== year(initial_investment_date),]$ticker)) < length(unique(test_ticker))
      #(!!!)
      
      
      
### Re -  Investing  Logic ###      

      
re_invest_df = hist_price_infl %>% group_by(ticker) %>% dplyr::mutate(yearly_stocks = cumsum(replace_na(Stocks, 0))) %>% select(ticker , Year, yearly_stocks) %>% group_by(ticker, Year) %>% filter(yearly_stocks == max(yearly_stocks))  %>% filter(Year == year(initial_investment_date))


divs_due_to_stocks_previous_years = sum(as.data.frame(left_join(re_invest_df,
          divs_agg[divs_agg$Year_div == year(initial_investment_date)+1  ,],
          by=c('ticker'='ticker')) %>% mutate(Div_income = div*yearly_stocks*taxed))$Div_income)   
      
               

df_inflation_reinvest  = df_inflation #to update the money input for the tickets, based on the already bought stocks and their divs


old <- Sys.time() # get start time


 for ( j in  seq.int(year(initial_investment_date)+1,year(final_investment_date)) ) {
   
   
   # CONSIDERATION: the first year no dividend will be generated, the second year, the stocks already acquired on Y1, will be generating additional income, that will be applied as EXTRA monetary input (proportionally every month, so /12) - assumming dividends come regularly, no in batches every Q.
   
   
   # as.data.frame(df_inflation %>% filter( Year == 2012))$money_input_infl 
   
   #Yearly:
   #as.data.frame(df_inflation %>% filter( Year == j))$money_input_infl_year+ divs_due_to_stocks_previous_years/12
   
   #For every ticket, the new inout of money:
   #as.data.frame(df_inflation %>% filter( Year == j))$money_input_infl + divs_due_to_stocks_previous_years/12/length(unique(test_ticker))
   

# df_inflation_reinvest[df_inflation_reinvest$Year ==2012  ,]$money_input_infl =   as.data.frame(df_inflation %>% filter( Year == 2012))$money_input_infl + divs_due_to_stocks_previous_years/12/length(unique(test_ticker))

   
     



df_inflation_reinvest[df_inflation_reinvest$Year == j  ,]$money_input_infl =   as.data.frame(df_inflation %>% filter( Year == j))$money_input_infl + divs_due_to_stocks_previous_years/12/length(unique(test_ticker))


df_inflation_reinvest[df_inflation_reinvest$Year == j  ,]$money_input_infl_year = as.data.frame(df_inflation %>% filter( Year == j))$money_input_infl_year + divs_due_to_stocks_previous_years/12
  


  
hist_price_infl_reinvest <- left_join(df_historical %>% filter( Year == j),
                                      df_inflation_reinvest %>% filter( Year == j) %>% select(Year, money_input_infl),
                                      by=c('Year')) 

hist_price_infl_reinvest$Stocks <- hist_price_infl_reinvest$money_input_infl/hist_price_infl_reinvest$price_close

       

# 
# 
# hist_price_infl_reinvest %>% group_by(ticker) %>% dplyr::mutate(yearly_stocks = cumsum(replace_na(Stocks, 0))) %>% select(ticker , Year, yearly_stocks) %>% group_by(ticker, Year) %>% filter(yearly_stocks == max(yearly_stocks))  


       

  re_invest_df <-   rbind(re_invest_df,
                          hist_price_infl_reinvest %>% group_by(ticker) %>% dplyr::mutate(yearly_stocks = cumsum(replace_na(Stocks, 0))) %>% select(ticker , Year, yearly_stocks) %>% group_by(ticker, Year) %>% filter(yearly_stocks == max(yearly_stocks))  
                          )
      
  
  

#Tthe total amount of the column Div_income can be used to buy further stocks (NOW ALL THAT YOU EVER BOUGHT) =>        
divs_due_to_stocks_previous_years = sum(as.data.frame(
                  left_join( re_invest_df %>% group_by(ticker) %>% dplyr::summarise(yearly_stocks = sum(yearly_stocks)),
                            divs_agg[divs_agg$Year_div == j  ,],
                            by=c('ticker'='ticker') ) %>%
                  mutate(Div_income = div*yearly_stocks*taxed))$Div_income) 
print(j)
 } #end for (!)






re_invest_df$cum_stocks_ticker =   as.data.frame(re_invest_df %>% group_by(ticker ) %>% 
                                dplyr::mutate(cum_stocks_ticker = cumsum(replace_na(yearly_stocks, 0))) 
                              %>% select(ticker , Year, cum_stocks_ticker))$cum_stocks_ticker


for ( z in  seq.int(year(final_investment_date)+1,year(ending_date)) ) {                    

  #re_invest_df %>% filter (Year==j)
  
   re_invest_df <-  rbind( re_invest_df,
                          re_invest_df %>% filter (Year==j) %>% 
                                dplyr::mutate(Year = z)  %>% 
                                dplyr::mutate(yearly_stocks  = 0)
                           )
      
  
}

new <- Sys.time() - old # calculate difference
print(new) # print in nice format


#money input comparison
              
                 plot_ly() %>% 
                    add_trace(data= df_inflation, name="Yearly Money input - No Re-inv", x = ~Year, y = ~money_input_infl_year, mode = "lines+markers", type = "scatter") %>%
                  add_trace(data= df_inflation_reinvest, name="Yearly Money input - Re-inv", x = ~Year, y = ~money_input_infl_year, mode = "lines+markers", type = "scatter") %>%   
                  layout(
                                  title = "<b>Historical Monetary Input<b>",
                                  xaxis = list(title="Year"),
                                  yaxis = list(title="($)")
                        )

#number of stocks bought comparison

                    # plot_ly() %>% 
                    # add_trace(data= hist_price_infl %>% group_by(ticker,Year) %>% dplyr::summarise(yearly_stocks = sum(Stocks)),
                    #           name="No Re-inv",
                    #           x = ~Year, y = ~yearly_stocks, name = ~ticker,
                    #           mode = "lines+markers", type = "scatter") %>%
                    # add_trace(data= re_invest_df,
                    #           name="Re-inv",
                    #         x = ~Year, y = ~yearly_stocks,
                    #         mode = "lines+markers", type = "scatter") %>%   
                    # layout(
                    #               title = "<b>Stocks Bought<b>",
                    #               xaxis = list(title="Year"),
                    #               yaxis = list(title="Stocks")
                    #     )
                    
                    fig1 <-   plot_ly() %>% 
                                   add_trace(
                                     data= hist_price_infl %>% group_by(ticker,Year) %>% 
                                       dplyr::summarise(yearly_stocks = sum(Stocks)),
                                    name= ~ticker,
                                    x = ~Year, y = ~yearly_stocks, name = ~ticker,
                                    mode = "lines+markers", type = "scatter")  %>%   
                    layout(
                                  xaxis = list(title="Year"),
                                  #yaxis = list(title="Stocks",range = c(0,55))
                                  yaxis = list(title="Stocks",range = c(0,  max(re_invest_df$yearly_stocks)*1.25 ))
                        ) #stocks bought per year - no reinv
                    
                    
                    fig2 <-  plot_ly() %>% 
                                  add_trace(data = as.data.frame(re_invest_df),
                                    x = ~Year, y = ~yearly_stocks,name= ~ticker,
                                     type = "scatter", mode = "lines+markers") %>% 
                                  #layout(yaxis = list(range = c(0,55)))
                                  layout(yaxis = list(range = c(0,max(re_invest_df$yearly_stocks)*1.25 )))
                        # stock bough per year - reinv
                    
                    annotations = list( 
                                          list( 
                                            x = 0.2,  
                                            y = 1.0,  
                                            text = "<b>Stocks Bought - No Re investment<b>",  
                                            xref = "paper",  
                                            yref = "paper",  
                                            xanchor = "center",  
                                            yanchor = "bottom",  
                                            showarrow = FALSE 
                                          ),  
                                          list( 
                                            x = 0.8,  
                                            y = 1,  
                                            text = "<b>Stocks Bought - Re investment<b>",  
                                            xref = "paper",  
                                            yref = "paper",  
                                            xanchor = "center",  
                                            yanchor = "bottom",  
                                            showarrow = FALSE 
                                          )
                                        )
                    
                    subplot(fig1, fig2) %>% layout(annotations = annotations) 
                    

#cumulative stocks comparison
                    

                    # plot_ly() %>% 
                    # add_trace(data=  hist_price_infl_group %>% group_by(ticker, Year) %>%
                    #             filter(cum_stocks_ticker == max(cum_stocks_ticker)) %>% 
                    #             dplyr::mutate(tickers = paste(ticker,'no-reinv')),
                    #           x = ~Year, y = ~cum_stocks_ticker, name = ~tickers,
                    #           mode = "markers", type = "scatter") %>%
                    # add_trace(data= re_invest_df %>% group_by(ticker ) %>% 
                    #             dplyr::mutate(cum_stocks_ticker = cumsum(replace_na(yearly_stocks, 0))) 
                    #           %>% select(ticker , Year, cum_stocks_ticker)  
                    #           %>% dplyr::mutate(tickers = paste(ticker,'Re- inv')),
                    #         x = ~Year, y = ~cum_stocks_ticker, name = ~tickers,
                    #         mode = "lines+markers", type = "scatter") %>%   
                    # layout(
                    #               title = "<b>HCumulative Stocks Comparison<b>",
                    #               xaxis = list(title="Year"),
                    #               yaxis = list(title="Stocks")
                    #     )
                     
                     
                    
                    
                      fig1 <-     plot_ly() %>% 
                                      add_trace(data=  as.data.frame(hist_price_infl_group %>% group_by(ticker, Year) %>%
                                      filter(cum_stocks_ticker == max(cum_stocks_ticker)) %>% 
                                      dplyr::mutate(tickers = paste(ticker,'no-reinv')) ),
                                    x = ~Year, y = ~cum_stocks_ticker, name = ~tickers,
                                    mode = "lines+markers", type = "scatter") %>%
                                layout(
                                              xaxis = list(title="Year"),
                                              #yaxis = list(title="Stocks",range = c(0,500))
                                              yaxis = list(title="Stocks",range = c(0,max(re_invest_df$cum_stocks_ticker)*1.25))
                                    )
                      # stocks per ticker cumulative - no reinv
                    
                      
                    # fig2 <-  plot_ly() %>% 
                    #               add_trace(data = as.data.frame(re_invest_df %>% group_by(ticker ) %>% 
                    #             dplyr::mutate(cum_stocks_ticker = cumsum(replace_na(yearly_stocks, 0))) 
                    #           %>% select(ticker , Year, cum_stocks_ticker)  
                    #           %>% dplyr::mutate(tickers = paste(ticker,'Re- inv')) ),
                    #         x = ~Year, y = ~cum_stocks_ticker, name = ~tickers,
                    #         mode = "lines+markers", type = "scatter")  %>%
                    #             layout(
                    #                           xaxis = list(title="Year"),
                    #                           yaxis = list(title="Stocks",range = c(0,500))
                    #                 )
                      
                       fig2 <-  plot_ly() %>% 
                                  add_trace(data = as.data.frame(re_invest_df %>% dplyr::mutate(tickers = paste(ticker,'Re- inv')) ),
                            x = ~Year, y = ~cum_stocks_ticker, name = ~tickers,
                            mode = "lines+markers", type = "scatter")  %>%
                                layout(
                                              xaxis = list(title="Year"),
                                              #yaxis = list(title="Stocks",range = c(0,500))
                                              yaxis = list(title="Stocks",range = c(0,max(re_invest_df$cum_stocks_ticker)*1.25))
                                    ) ## stocks per ticker cumulative - no reinv
                    
                    annotations = list( 
                                          list( 
                                            x = 0.2,  
                                            y = 1.0,  
                                            text = "<b>Cumulative Stocks - No Re investment<b>",  
                                            xref = "paper",  
                                            yref = "paper",  
                                            xanchor = "center",  
                                            yanchor = "bottom",  
                                            showarrow = FALSE 
                                          ),  
                                          list( 
                                            x = 0.8,  
                                            y = 1,  
                                            text = "<b>Cumulative Stocks - Re investment<b>",  
                                            xref = "paper",  
                                            yref = "paper",  
                                            xanchor = "center",  
                                            yanchor = "bottom",  
                                            showarrow = FALSE 
                                          )
                                        )
                    
                    subplot(fig1, fig2) %>% layout(annotations = annotations) 
                    
                    

                  
                    
                    
#dividend comparison       
                    
       
                      fig1 <- plot_ly() %>% 
                                      add_trace(data =  as.data.frame(
                                         left_join(divs_agg,
                              hist_price_infl_group %>% group_by(ticker, Year)
                              %>% filter(cum_stocks_ticker == max(cum_stocks_ticker)), 
                              by=c('ticker'='ticker','Year_div'='Year')) %>% 
                                dplyr::mutate(dividend = cum_stocks_ticker*div) %>% 
                         group_by( ticker, Year_div ) %>% filter(row_number()==1)  %>%  group_by(  Year_div ) 
                         %>%  dplyr::summarise(Total_Yearly_Div_NoReinv = replace_na(sum(dividend),0))
                      
                                      ),
                                    x = ~Year_div, y = ~Total_Yearly_Div_NoReinv,
                                    mode = "lines+markers", type = "scatter") %>%
                                layout(
                                              xaxis = list(title="Year"),
                                              yaxis = list(title="Stocks",range = c(0,40000))
                                    )
                    

                    fig2 <-  plot_ly() %>% 
                                  add_trace(data= as.data.frame(
                                               left_join(divs_agg ,
                                                      re_invest_df, 
                                                      by=c('ticker'='ticker','Year_div'='Year'))  %>% 
                                                 dplyr::mutate(dividend = cum_stocks_ticker*div) %>% 
                                                 group_by( Year_div ) %>%
                                                 dplyr::summarise(Total_Yearly_Div_Reinv = replace_na(sum(dividend),0))
                                                      ),
                            x = ~Year_div, y = ~Total_Yearly_Div_Reinv,
                            mode = "lines+markers", type = "scatter")  %>%
                                layout(
                                              xaxis = list(title="Year"),
                                              yaxis = list(title="Stocks",range = c(0,50000))
                                    )
                    
                    annotations = list( 
                                          list( 
                                            x = 0.2,  
                                            y = 1.0,  
                                            text = "<b>Dividend Yearly - No Re investment<b>",  
                                            xref = "paper",  
                                            yref = "paper",  
                                            xanchor = "center",  
                                            yanchor = "bottom",  
                                            showarrow = FALSE 
                                          ),  
                                          list( 
                                            x = 0.8,  
                                            y = 1,  
                                            text = "<b>Dividend Yearly - Re investment<b>",  
                                            xref = "paper",  
                                            yref = "paper",  
                                            xanchor = "center",  
                                            yanchor = "bottom",  
                                            showarrow = FALSE 
                                          )
                                        )
                    
                    subplot(fig1, fig2) %>% layout(annotations = annotations) 
                    
                    
                    
                          
                      fig1 <- plot_ly() %>% 
                                      add_trace(data =  as.data.frame(
                                         left_join( divs_agg,
                              hist_price_infl_group %>% group_by(ticker, Year)
                              %>% filter(cum_stocks_ticker == max(cum_stocks_ticker)), 
                              by=c('ticker'='ticker','Year_div'='Year')) %>% 
                                dplyr::mutate(dividend = cum_stocks_ticker*div) %>% 
                         group_by( ticker, Year_div ) %>% filter(row_number()==1)  
                                      ),
                                    x = ~Year_div, y = ~dividend, name = ~ticker,
                                    mode = "none", type = "scatter", stackgroup = 'one') %>%
                                layout(
                                              xaxis = list(title="Year"),
                                              yaxis = list(title="Stocks",range = c(0,10000))
                                    )
                    

                    fig2 <-  plot_ly() %>% 
                                  add_trace(data= as.data.frame(
                                               left_join(divs_agg ,
                                                      re_invest_df, 
                                                      by=c('ticker'='ticker','Year_div'='Year'))  %>% 
                                                 dplyr::mutate(dividend = cum_stocks_ticker*div) 
                                                      ),
                            x = ~Year_div, y = ~dividend, name = ~ticker,
                            mode = "none", type = "scatter", stackgroup = 'one')  %>%
                                layout(
                                              xaxis = list(title="Year"),
                                              yaxis = list(title="Stocks",range = c(0,10000))
                                    )
                    
                    annotations = list( 
                                          list( 
                                            x = 0.2,  
                                            y = 1.0,  
                                            text = "<b>Dividend Yearly - No Re investment<b>",  
                                            xref = "paper",  
                                            yref = "paper",  
                                            xanchor = "center",  
                                            yanchor = "bottom",  
                                            showarrow = FALSE 
                                          ),  
                                          list( 
                                            x = 0.8,  
                                            y = 1,  
                                            text = "<b>Dividend Yearly - Re investment<b>",  
                                            xref = "paper",  
                                            yref = "paper",  
                                            xanchor = "center",  
                                            yanchor = "bottom",  
                                            showarrow = FALSE 
                                          )
                                        )
                    
                    subplot(fig1, fig2) %>% layout(annotations = annotations) 
                    
                    
                    
                    
                    
# Differences: re-investing dividends and not doing it                    
                    
                    re_investing_gains = as.data.frame(
                       left_join(divs_agg ,
                              re_invest_df %>% group_by(ticker ) %>% 
                                dplyr::mutate(cum_stocks_ticker = cumsum(replace_na(yearly_stocks, 0))), 
                              by=c('ticker'='ticker','Year_div'='Year'))  %>% 
                                dplyr::mutate(dividend = cum_stocks_ticker*div) %>% 
                         group_by( Year_div ) %>%  dplyr::summarise(Total_Yearly_Div_Reinv = replace_na(sum(dividend),0))
                      )$Total_Yearly_Div_Reinv                    /
                     as.data.frame(
                       left_join(divs_agg,
                              hist_price_infl_group %>% group_by(ticker, Year)
                              %>% filter(cum_stocks_ticker == max(cum_stocks_ticker)), 
                              by=c('ticker'='ticker','Year_div'='Year')) %>% 
                                dplyr::mutate(dividend = cum_stocks_ticker*div) %>% 
                         group_by( Year_div ) %>%  dplyr::summarise(Total_Yearly_Div_NoReinv = replace_na(sum(dividend),0))
                     )$Total_Yearly_Div_NoReinv
                       
                     
                      
                     
                     
                    plot_ly() %>% 
                    add_trace(data = data.frame(Year=(year(initial_date)):(year(ending_date)),
                                                re_investing_gains %>% replace(is.na(.), 0) ),
                              x = ~Year, y = ~re_investing_gains,
                              mode = "line+markers", type = "scatter") %>%
                    layout(
                                  title = "<b>Dividend Gap when Re-Investing<b>",
                                  xaxis = list(title="Year"),
                                  yaxis = list(title="Difference (%)")
                        )
                    
                    
# money input vs dividend (no-reinvest)
                    
                    
          
                 plot_ly() %>% 
                    add_trace(data= df_inflation, name="Yearly Money input - No Re-inv",
                              x = ~Year, y = ~money_input_infl_year*12, mode = "lines+markers", type = "scatter") %>%
                    add_trace(data =  as.data.frame(
                                         left_join(divs_agg,
                              hist_price_infl_group %>% group_by(ticker, Year)
                              %>% filter(cum_stocks_ticker == max(cum_stocks_ticker)), 
                              by=c('ticker'='ticker','Year_div'='Year')) %>% 
                                dplyr::mutate(dividend = cum_stocks_ticker*div) %>% 
                         group_by( ticker, Year_div ) %>% filter(row_number()==1)  %>%  group_by(  Year_div ) 
                         %>%  dplyr::summarise(Total_Yearly_Div_NoReinv = replace_na(sum(dividend),0))
                      
                                      ),
                                    x = ~Year_div, y = ~Total_Yearly_Div_NoReinv,
                                    name="Yearly Dividend - No Re-inv",
                                    mode = "lines+markers", type = "scatter") %>%   
                  layout(
                                  title = "<b>Cash Flow - No re-inv<b>",
                                  xaxis = list(title="Year"),
                                  yaxis = list(title="($)")
                        )          

                    
# money input vs dividend (reinvest)                                       
                    
                 
                 plot_ly() %>% 
                   add_trace(data= as.data.frame(
                                               left_join(divs_agg ,
                                                      re_invest_df, 
                                                      by=c('ticker'='ticker','Year_div'='Year'))  %>% 
                                                 dplyr::mutate(dividend = cum_stocks_ticker*div) %>% 
                                                 group_by( Year_div ) %>%
                                                 dplyr::summarise(Total_Yearly_Div_Reinv = replace_na(sum(dividend),0))
                                                      ),
                            x = ~Year_div, y = ~Total_Yearly_Div_Reinv, name="Yearly Dividend - No Re-inv",
                            mode = "lines+markers", type = "scatter") %>% 
                  add_trace(data= df_inflation_reinvest, name="Yearly Money input - Re-inv", x = ~Year, y = ~money_input_infl_year*12, mode = "lines+markers", type = "scatter") %>%   
                  layout(
                                  title = "<b>Cash Flow - re-inv<b>",
                                  xaxis = list(title="Year"),
                                  yaxis = list(title="($)")
                        )
                 
                 
# money input vs dividend (no-reinvest) CUMULATIVE                                       
                    
                 
                 plot_ly() %>% 
                   add_trace(data= as.data.frame(
                                               left_join(divs_agg ,
                                                      re_invest_df, 
                                                      by=c('ticker'='ticker','Year_div'='Year'))  %>% 
                                                 dplyr::mutate(dividend = cum_stocks_ticker*div) %>% 
                                                 group_by( Year_div ) %>%
                                                 dplyr::summarise(Total_Yearly_Div_Reinv = replace_na(sum(dividend),0))
                                                      ) %>%
                              dplyr::mutate(cum_Total_Yearly_Div_Reinv = cumsum(Total_Yearly_Div_Reinv)),
                            x = ~Year_div, y = ~cum_Total_Yearly_Div_Reinv, name="Yearly Dividend - No Re-inv",
                            mode = "lines+markers", type = "scatter") %>% 
                  add_trace(data= df_inflation_reinvest %>%
                              dplyr::mutate(cum_money_input_infl_year = cumsum(money_input_infl_year*12)),
                            name="Yearly Money input - Re-inv", x = ~Year, y = ~cum_money_input_infl_year, mode = "lines+markers", type = "scatter") %>%   
                  layout(
                                  title = "<b>Cash Flow - re-inv<b>",
                                  xaxis = list(title="Year"),
                                  yaxis = list(title="($)")
                        )            
                 
                 
                 
            
      
```


```{r Portfolio DCA - test}


# set as direction the one of .Rmd archive; .xlsx and .Rmd mut be on same folder
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
my_portfolio <- read_excel("Portfolio.xlsx", sheet="portfolio1")
# clear empty cells in my_data; overwrite it
my_portfolio <- na.omit(my_portfolio)

my_portfolio$Ticker <- sub("NASDAQ:", "", my_portfolio$Ticker)
my_portfolio$Ticker <- sub("NYSE:", "", my_portfolio$Ticker)


colnames(my_portfolio) <- c('ticker','DCA','Amount')



my_portfolio$DCA = as.numeric(  gsub(",", "", my_portfolio$DCA) ) /100
my_portfolio$Invested <- my_portfolio$DCA*my_portfolio$Amount


initial_date="2010-01-01" #year(initial_date)
ending_date="2022-12-31"

## Given tickers and buy dates, provide the avg yield per ticker on the moment of buy ##


      df_historical <- yf_get(tickers = my_portfolio$ticker,          ### yfr ###
                              first_date= initial_date,
                              last_date= ending_date,
                              thresh_bad_data = 0.2,
                              freq_data="monthly") %>% select(ticker, price_close, ref_date)
      
      


      df_DCA = merge(df_historical, my_portfolio, by = "ticker")
      
         
     df_DCA$ticker_dca <- paste('DCA',df_DCA$ticker)

      # plot_ly(df_DCA, type = 'scatter', mode = 'lines') %>%
      #               add_trace(x = ~ref_date, y = ~price_close, name = ~ticker)
      # 
      # 
      # plot_ly(df_DCA %>% filter(ticker == 'KO'), type = 'scatter', mode = 'lines') %>%
      #               add_trace(x = ~ref_date, y = ~price_close, name = ~ticker)
      
   
      
    #%>% filter(ticker == 'KO')
     
      # plot_ly(df_DCA ) %>%
      #       add_trace(x = ~ref_date, y = ~price_close, type = 'scatter', mode = "lines", name = ~ticker)%>%
      #     add_trace(x = ~ref_date, y = ~DCA, type = 'scatter', mode = "lines", name = ~ticker_dca)%>%
      #                   layout(title = '<b> DCA <b>', xaxis = list(title = 'Date'), 
      #                            yaxis = list(title = 'Price ($)'), legend = list(title=list(text='<b> Ticker </b>')))
      

  
      
    # plot_ly(df_DCA ) %>%
    #         add_trace(x = ~ref_date, y = ~price_close, type = 'scatter', mode = "lines", name = ~ticker)%>%
    #       add_trace(x = ~ref_date, y = ~DCA, type = 'scatter', mode = "lines", yaxis = "y2", name = ~ticker_dca)%>%
    #                     layout(title = '<b> DCA <b>', xaxis = list(title = 'Date'), 
    #                              yaxis = list(title = 'Price ($)'), legend = list(title=list(text='<b> Ticker </b>')),
    #                             yaxis2 = list(overlaying = "y", side = "right",automargin = T,title = "DCA ($)"))
          
    # class(df_DCA$price_close)
    # class(df_DCA$DCA)  
    # class(as.numeric(df_DCA$DCA))  
    # 
    # as.numeric(as.character(df_DCA$DCA))  
    
     #df_DCA$DCA = as.numeric(  gsub(",", "", df_DCA$DCA) ) /100
    
    
      plot_ly(df_DCA ) %>%
            add_trace(x = ~ref_date, y = ~price_close, type = 'scatter', mode = "lines", name = ~ticker)%>%
          add_trace(x = ~ref_date, y = ~DCA, type = 'scatter', mode = "lines", name = ~ticker_dca)%>%
                        layout(title = '<b> DCA <b>', xaxis = list(title = 'Date'),
                                 yaxis = list(title = 'Price ($)'), legend = list(title=list(text='<b> Ticker </b>')))
      
  
    

    
   


```


```{r Dividend Proyection - test}


    
source("R_Stocks_Analysis_functions.R")  
    
#divs_agg <- f_divs_agg( c('TROW','PG'), "2010-01-01","2022-12-31")    
divs_agg <- f_divs_agg(my_portfolio$ticker, "2010-01-01","2022-12-31")    



### test ###

zzz = divs_agg %>% group_by( ticker ) %>% 
            mutate( growth = ( div/lag(div) -1)*100 )

  


zzz = zzz %>% group_by( ticker ) %>% filter(row_number()>1)

zzz %>% 
  group_by(ticker) %>%  
  summarise(quantile = scales::percent(c(0.25, 0.5, 0.75)),
            Growth = quantile(growth, c(0.25, 0.5, 0.75)))

zzz %>% 
  group_by(ticker) %>%  
  dplyr::summarise(enframe(quantile(growth, c(0.25, 0.35, 0.5)), "quantile", "Growth"))



xyz = zzz %>% 
  group_by(ticker) %>%  
  dplyr::summarise(enframe(quantile(growth, c(0.25, 0.35, 0.5)), "quantile", "Growth")) %>%
  filter(quantile == '50%')





divs_agg %>% group_by( ticker ) %>% 
            mutate( growth = ( div/lag(div) -1)*100 ) %>% group_by( ticker ) %>% filter(row_number()>1)  %>% 
            group_by(ticker) %>%  
            dplyr::summarise(enframe(quantile(growth, c(0.25, 0.35, 0.5)), "quantile", "Growth")) %>%
           filter(quantile == '50%')


      # divs_agg %>% 
      #     group_by(ticker) %>% slice(n())
       
       # divs_agg %>% 
       #    group_by(ticker) %>%  slice(1:(n() - 10))  

### end test ###


df_growth_portfolio_fcst <- Reduce(function (...) { merge(..., all = FALSE) },   # Inner join
                        list(divs_agg %>% group_by( ticker ) %>% 
                                    mutate( growth = ( div/lag(div) -1)*100 ) %>% group_by( ticker ) %>% filter(row_number()>1)  %>% 
                                    group_by(ticker) %>%  
                                    dplyr::summarise(enframe(quantile(growth, c(0.25, 0.35, 0.5)), "quantile", "Growth")) %>%
                                   filter(quantile == '25%'),
                             my_portfolio,
                              divs_agg %>% 
                                 group_by(ticker) %>% slice(n())  
                           )
        )


df_growth_portfolio_fcst$Current_div <- df_growth_portfolio_fcst$Amount * df_growth_portfolio_fcst$div


df_growth_portfolio_fcst$Expected_div <- df_growth_portfolio_fcst$Current_div  * (1 + df_growth_portfolio_fcst$Growth/100)
       
       
sum(df_growth_portfolio_fcst$Expected_div) / sum(df_growth_portfolio_fcst$Current_div)



#################
# Using the UDF #
#################
    
source("R_Stocks_Analysis_functions.R")  

df_growth_portfolio_fcst <- f_growth_portfolio_fcst(divs_agg,0.35)
sum(df_growth_portfolio_fcst$Expected_div) / sum(df_growth_portfolio_fcst$Current_div)



df_growth_portfolio_fcst <- f_growth_portfolio_fcst(divs_agg,0.5)
sum(df_growth_portfolio_fcst$Expected_div) / sum(df_growth_portfolio_fcst$Current_div)



Perc <- c(0.25, 0.35,0.45, 0.5,0.55, 0.65 , 0.75)


growth_fcst_consolidated = f_growth_portfolio_fcst(divs_agg,Perc) %>% 
         group_by(quantile)  %>%  dplyr::summarise(
                                            Expected_Growth  = 100*(replace_na(sum(Expected_div ),0) / replace_na(sum(Current_div ),0) -1)
                                            )
      
      plot_ly(growth_fcst_consolidated, type = 'bar')%>%
                          add_trace(x = ~quantile, y = ~Expected_Growth , name = 'Expected Yearly Growth')%>%
                          layout(title = '<b>Portfolio - Expected Dividend Growth<b>', xaxis = list(title = 'Percentiles'), 
                       yaxis = list(title = 'Dividend Growth (%)'), legend = list(title=list(text='<b> Legend </b>')))





```

```{r Yield on Buy}

## Given tickers and buy dates, provide the avg yield per ticker on the moment of buy
# This will show the effects of the dividend growth




```


```{r export data}

#save the pulled data for later use



```



```{r import local data}

#No internet access to fetch the data? Use this chunk to import already downloaded data



```



```{r import xml data}
# 
# install.packages("XML")
# 
# 
# library(XML)
# url <- "https://www.opencodez.com/"
# source <- readLines(url, encoding = "UTF-8")
# parsed_doc <- htmlParse(source, encoding = "UTF-8")
# xpathSApply(parsed_doc, path = '/html/body/div[2]/div/div/div/div[1]/div[1]/article[1]/header/h2/a', xmlValue)
# 
# 


```
